### ISSUE TITLE
benchmark NWP based forecasts

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-core#10]
Issue for tracking general info related to benchmark forecasts.

Incomplete list of data availability:

Model | Grid | Source | Total Cloud Cover | GHI | DNI/DHI | Period of Record
-- | -- | -- | -- | -- | -- | --
GFS | 0.5 deg | NOMADS TDS | 3/6 hr mixed interval average | 3/6 hr mixed interval average | None | -2 years to present
GFS | 0.5 deg | Unidata TDS | 3/6 hr mixed interval average | 3/6 hr mixed interval average | None | -30 days to present
NAM | 12 km | NOMADS TDS | 1 (3) hr for 36 (84) hr | 1 (3) hr for 36 (84) hr | None | -1 year to present
NAM | 12 km |   | 1 (3) hr for 36 (84) hr | 1 (3) hr for 36 (84) hr | None | -30 days to present
RAP | 13 km | NOMADS TDS | 1 hr | None | None | -1 year to present
RAP | 13 km | Unidata TDS | 1 hr | None | None | -30 days to present
HRRR | 3 km | Unidata TDS | 1 hr | None | None | -4 days to present
HRRR | 3 km | NCEP DODS | 1 hr | 1 hr | 1 hr | -1 days to present
HRRR | 3 km | NCEP g2sub | None | 15 min | 15 min | -1 days to present

List of methods for converting different inputs into different outputs:

Input | Method | Output (Power)
-- | -- | --
15 min GHI, DNI | I -> P | 15 min or hr avg
15 min GHI | I -> DISC -> P | 15 min or hr avg
1 hr GHI | I -> DISC -> P | 1 hr
1 hr GHI | I -> CSI -> sub-hrly CSI -> I -> DISC -> P | 1 hr avg
1 hr CC | CC -> sub-hrly CC -> Larson -> P | 1 hr avg
3/6 GHI | X | X
3/6 CC | 3/6 CC -> sub-hrly CC -> Larson -> P | 1 hr avg
3/6 CC | 3/6 CC -> 3 hr CC -> sub-hrly CC -> Larson -> P | 1 hr avg

**Comment by wholmgren** [comment]
More observations:

* `pvlib.forecast` ties to together the data gathering and the data processing. This is not entirely unreasonable because the data availability puts requirements on the processing (as show above). However, `pvlib.forecast` goes too far and it may be difficult to cleanly adapt it to our needs. 
* `pvlib.forecast.get_processed_data` is super convenient. 
* If a total rewrite of `pvlib.forecast` is in order, [250 lines of processing code](https://github.com/pvlib/pvlib-python/blob/master/pvlib/forecast.py#L393-L648) can be reused here with relatively minor modifications. The implementation questions are how to handle `Location` objects and if functions/methods args should be one or more Series or a DataFrames with certain keys. 
* The `ModelChain.complete_irradiance` and `ModelChain.prepare_inputs` methods could be extended/complemented. This might be a good way of addressing the implementation questions in the previous point.
* Some of the weather processing code is probably implemented in MetPy, but using MetPy usually means using Pint units, and that's irritating.
* @cwhanse  wrote ARIMA code in https://github.com/pvlib/pvlib-python/pull/543 but it might be easiest to move that over here for the next 6 months.

**Comment by wholmgren** [comment]
Consistently using NOAA g2sub seems like the best option for getting data. We can archive gridded CONUS data for all but subhourly HRRR.

root for g2sub http calls below: https://nomads.ncep.noaa.gov/cgi-bin/


GFS
---

0.25 deg route: filter_gfs_0p25_1hr.pl
files named like: gfs.t{INITTIME}z.pgrb2.0p25.f{FORECASTHOUR}

FORECASTHOUR = 0 does not have cloud cover

Variable: Total_cloud_cover_entire_atmosphere_1_Hour_Average
:abbreviation: "TCDC"  # TCDC also used by low, mid, high, convective, and boundary
specify "lev_entire_atmosphere=on" NOT "lev_entire_atmosphere_as_a_single_layer=on"
https://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_0p25_1hr.pl?file=gfs.t12z.pgrb2.0p25.f001&lev_entire_atmosphere=on&var_TCDC=on&subregion=&leftlon=-126&rightlon=-66&toplat=50&bottomlat=24&dir=%2Fgfs.2019040112

Variable: Temperature_height_above_ground
:abbreviation: "TMP"
specify "lev_2_m_above_ground=on"
https://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_0p25_1hr.pl?file=gfs.t12z.pgrb2.0p25.f001&lev_2_m_above_ground=on&var_TMP=on&var_UGRD=on&var_VGRD=on&subregion=&leftlon=-126&rightlon=-66&toplat=50&bottomlat=24&dir=%2Fgfs.2019040112

Variable: u-component_of_wind_height_above_ground
:abbreviation: "UGRD"
specify "lev_10_m_above_ground=on"
Variable: v-component_of_wind_height_above_ground
:abbreviation: "VGRD"
specify "lev_10_m_above_ground=on"
https://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_0p25_1hr.pl?file=gfs.t12z.pgrb2.0p25.f001&lev_10_m_above_ground=on&lev_2_m_above_ground=on&var_TMP=on&var_UGRD=on&var_VGRD=on&subregion=&leftlon=-126&rightlon=-66&toplat=50&bottomlat=24&dir=%2Fgfs.2019040112

all of the above:
https://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_0p25_1hr.pl?file=gfs.t12z.pgrb2.0p25.f001&lev_10_m_above_ground=on&lev_2_m_above_ground=on&lev_entire_atmosphere=on&var_TCDC=on&var_TMP=on&var_UGRD=on&var_VGRD=on&subregion=&leftlon=-126&rightlon=-66&toplat=50&bottomlat=24&dir=%2Fgfs.2019040112
124 KB file with the 4 variables
File has a "height_above_ground" and "height_above_ground1" - one for temp and one for wind. Probably ok to ignore.

120 hours at 1 hr resolution. 120 * 124 KB = 15 MB
240 hours at 3 hr resolution. 384/3 * 124 KB = 10 MB
384 hours at 12 hr resolution. 384/3 * 124 KB = 4 MB

25 MB / run * 4 runs / day = 100 MB / day


IF we also want GFS GHI...

Variable: Downward_Short-Wave_Radiation_Flux_surface
:abbreviation: "DSWRF"
specify "lev_surface=on"
https://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_0p25_1hr.pl?file=gfs.t12z.pgrb2.0p25.f001&lev_surface=on&var_DSWRF=on&subregion=&leftlon=-126&rightlon=-66&toplat=50&bottomlat=24&dir=%2Fgfs.2019040112

If combining with all of the above, you'll also get temperature_surface whether you like it or not.

https://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_0p25_1hr.pl?file=gfs.t12z.pgrb2.0p25.f001&lev_10_m_above_ground=on&lev_2_m_above_ground=on&lev_entire_atmosphere=on&lev_surface=on&var_DSWRF=on&var_TCDC=on&var_TMP=on&var_UGRD=on&var_VGRD=on&subregion=&leftlon=-126&rightlon=-66&toplat=50&bottomlat=24&dir=%2Fgfs.2019040112

This file is 175 KB.

Both cloud cover and GHI are mixed intervals average. Pattern is:

f001 = 1 hour average
f002 = 2 hour average
f003 = 3 hour average
f004 = 4 hour average
f005 = 5 hour average
f006 = 6 hour average
f007 = 1 hour average
f008 = 2 hour average...



NAM
---

12 km route: filter_nam.pl?dir=%2Fnam.20190401
files named like: nam.t{INITTIME}z.awphys{FORECASTHOUR}.tm00.grib2

Variable: Total_cloud_cover_entire_atmosphere_single_layer
:abbreviation: "TCDC"
specify "lev_entire_atmosphere_as_a_single_layer=on" NOT "lev_entire_atmosphere=on"

Variable: Temperature_height_above_ground
:abbreviation: "TMP"
specify "lev_2_m_above_ground=on"

Variable: u-component_of_wind_height_above_ground
:abbreviation: "UGRD"
specify "lev_10_m_above_ground=on"

Variable: v-component_of_wind_height_above_ground
:abbreviation: "VGRD"
specify "lev_10_m_above_ground=on"

Variable: Downward_Short-Wave_Radiation_Flux_surface
:abbreviation: "DSWRF"
specify "lev_surface=on"

https://nomads.ncep.noaa.gov/cgi-bin/filter_nam.pl?file=nam.t00z.awphys01.tm00.grib2&lev_10_m_above_ground=on&lev_2_m_above_ground=on&lev_entire_atmosphere_%5C%28considered_as_a_single_layer%5C%29=on&lev_surface=on&var_DSWRF=on&var_TCDC=on&var_TMP=on&var_UGRD=on&var_VGRD=on&subregion=&leftlon=-126&rightlon=-66&toplat=50&bottomlat=24&dir=%2Fnam.20190401

If combining all of the above, you'll also get temperature_surface whether you like it or not.

This file is 1.1 MB

36 hours at 1 hr resolution. 36 * 1.1 MB = 40 MB
84 hours at 3 hr resolution. 84/3 * 1.1 MB = 30.8 MB
36-84 hours at 3 hr resolution. (84 - 36)/3 * 1.1 = 18 MB

60 MB / run * 4 runs / day = 240 MB / day



RAP
---

RAP output is in files like:
* rap.t00z.awp130bgrbf01.grib2
* rap.t00z.awp130pgrbf01.grib2

The p files are available in g2sub. The b files are not.
The b files contain GHI (DSWRF), but the files do not.

RAP does not have DNI or DHI.

13 km route: filter_rap.pl?dir=%2Frap.20190401
files named like: rap.t{INITTIME}z.awp130pgrbf{FORECASTHOUR}.grib2

Variable: Total_cloud_cover_entire_atmosphere
:abbreviation: "TCDC"
specify "lev_entire_atmosphere=on" NOT "lev_entire_atmosphere_as_a_single_layer=on"

Variable: Temperature_height_above_ground
:abbreviation: "TMP"
specify "lev_2_m_above_ground=on"

Variable: u-component_of_wind_height_above_ground
:abbreviation: "UGRD"
specify "lev_10_m_above_ground=on"

Variable: v-component_of_wind_height_above_ground
:abbreviation: "VGRD"
specify "lev_10_m_above_ground=on"

https://nomads.ncep.noaa.gov/cgi-bin/filter_rap.pl?file=rap.t00z.awp130pgrbf01.grib2&lev_10_m_above_ground=on&lev_2_m_above_ground=on&lev_entire_atmosphere=on&lev_surface=on&var_TCDC=on&var_TMP=on&var_UGRD=on&var_VGRD=on&subregion=&leftlon=-126&rightlon=-66&toplat=50&bottomlat=24&dir=%2Frap.20190401

If combining all of the above, you'll also get temperature_surface whether you like it or not.

This file is 591 KB

21 hours at 1 hour resolution. 21 * 591 KB = 12 MB
39 hours at 1 hour resolution (3Z, 9Z, 15Z, 21Z). 39 * 591 KB = 23 MB

12 MB / run * 18 runs / day + 23 MB / run * 4 runs / day = 308 MB / day




HRRR
----

route: filter_hrrr_2d.pl?dir=%2Fhrrr.20190401%2Fconus
files named like: hrrr.t{INITTIME}.wrfsfcf{FORECASTHOUR}.grib2

Variable: Downward_Short-Wave_Radiation_Flux_surface
:abbreviation: "DSWRF"
specify "lev_surface=on"

Variable: Total_cloud_cover_entire_atmosphere
:abbreviation: "TCDC"
specify "lev_entire_atmosphere=on" NOT "lev_entire_atmosphere_as_a_single_layer=on"

Variable: Temperature_height_above_ground
:abbreviation: "TMP"
specify "lev_2_m_above_ground=on"

Variable: u-component_of_wind_height_above_ground
:abbreviation: "UGRD"
specify "lev_10_m_above_ground=on"

Variable: v-component_of_wind_height_above_ground
:abbreviation: "VGRD"
specify "lev_10_m_above_ground=on"

Visible_Beam_Downward_Solar_Flux_surface
:abbreviation: "VBDSF"
specify "lev_surface=on"

Visible_Diffuse_Downward_Solar_Flux_surface
:abbreviation: "VDDSF"
specify "lev_surface=on"

https://nomads.ncep.noaa.gov/cgi-bin/filter_hrrr_2d.pl?file=hrrr.t00z.wrfsfcf01.grib2&lev_10_m_above_ground=on&lev_2_m_above_ground=on&lev_entire_atmosphere=on&lev_surface=on&var_DSWRF=on&var_TCDC=on&var_TMP=on&var_UGRD=on&var_VBDSF=on&var_VDDSF=on&var_VGRD=on&subregion=&leftlon=-126&rightlon=-66&toplat=50&bottomlat=24&dir=%2Fhrrr.20190401%2Fconus

This file is 20.5 MB

18 hours at 1 hour resolution. 18 * 20.5 MB = 369 MB
36 hours at 1 hour resolution (0Z, 6Z, 12Z, 18Z). 36 * 20.5 MB = 738 MB

369 MB / run * 18 runs / day + 738 MB / run * 4 runs / day = 9.6 GB / day
9.6 GB / day * 365 days = 3.5 TB / year



HRRR Sub Hourly
---------------

route: filter_hrrr_sub.pl?dir=%2Fhrrr.20190401%2Fconus
files named like: hrrr.t{INITTIME}.wrfsubhf{FORECASTHOUR}.grib2

Cloud cover not available in subhourly files (not that we're likely to want it)

Variable: Downward_Short-Wave_Radiation_Flux_surface
:abbreviation: "DSWRF"
specify "lev_surface=on"

Variable: Temperature_height_above_ground
:abbreviation: "TMP"
specify "lev_2_m_above_ground=on"

Variable: u-component_of_wind_height_above_ground
:abbreviation: "UGRD"
specify "lev_10_m_above_ground=on"

Variable: v-component_of_wind_height_above_ground
:abbreviation: "VGRD"
specify "lev_10_m_above_ground=on"

Visible_Beam_Downward_Solar_Flux_surface
:abbreviation: "VBDSF"
specify "lev_surface=on"

Visible_Diffuse_Downward_Solar_Flux_surface
:abbreviation: "VDDSF"
specify "lev_surface=on"

https://nomads.ncep.noaa.gov/cgi-bin/filter_hrrr_sub.pl?file=hrrr.t00z.wrfsubhf01.grib2&lev_10_m_above_ground=on&lev_2_m_above_ground=on&lev_entire_atmosphere=on&lev_surface=on&var_DSWRF=on&var_TMP=on&var_UGRD=on&var_VBDSF=on&var_VDDSF=on&var_VGRD=on&subregion=&leftlon=-126&rightlon=-66&toplat=50&bottomlat=24&dir=%2Fhrrr.20190401%2Fconus

This file is 103.1 MB

18 hours at 1 hour resolution. 18 * 20.5 MB = 1.9 GB
36 hours at 1 hour resolution (0Z, 6Z, 12Z, 18Z). 36 * 20.5 MB = 3.7 GB

1.9 GB / run * 18 runs / day + 3.7 GB / run * 4 runs / day = 48 GB / day
48 GB / day * 365 days = 17.6 TB / year

It contains 15 minute intervals of the following fields:

* Downward_short-wave_radiation_flux_surface
* Downward_short-wave_radiation_flux_surface_15_Minute_Average
* Temperature_height_above_ground
* u-component_of_wind_height_above_ground
* u-component_of_wind_height_above_ground_5_Minute_Average
* v-component_of_wind_height_above_ground
* v-component_of_wind_height_above_ground_5_Minute_Average
* Visible_Beam_Downward_Solar_Flux_surface
* Visible_Beam_Downward_Solar_Flux_surface_15_Minute_Average
* Visible_Diffuse_Downward_Solar_Flux_surface

**Comment by wholmgren** [comment]
GEFS is available in three relevant varieties: 1.0 degree, 0.5 degree, and 0.5 degree bias corrected.

Seems that 0.5 degree bias corrected only has mean TCDC. It has p10, p50, p90, std. dev. for other fields. It also does not have TCDC in the individual member forecasts.

The 0.5 degree (raw) has mean, std. dev., and individual member TCDC. 

root: `https://nomads.ncep.noaa.gov/cgi-bin/filter_gens_0p50.pl`

file spec: `file=ge{STAT_OR_MEMBER}.t{INIT_TIME}z.pgrb2a.0p50.f{FORECAST_HOUR}`

`STAT_OR_MEMBER` is one of `avg`, `c00`, `p[1-2][1-9]`, `spr`

Get ensemble mean cloud cover, 2 m temp, 10 m winds:

https://nomads.ncep.noaa.gov/cgi-bin/filter_gens_0p50.pl?file=geavg.t00z.pgrb2a.0p50.f003&lev_10_m_above_ground=on&lev_2_m_above_ground=on&lev_entire_atmosphere=on&var_TCDC=on&var_TMP=on&var_UGRD=on&var_VGRD=on&subregion=&leftlon=-126&rightlon=-66&toplat=50&bottomlat=24&dir=%2Fgefs.20190410%2F00%2Fpgrb2ap5

This file is 33 KB. That's about 1/5 the size of the 0.25 deg GFS file, but we have ~20x more things (avg, control, spread, members). So getting data for all 0.5 deg GEFS members would be ~4x size of 0.25 deg GFS. That's doable. 

Online data archive is only last 7 days.

**Comment by alorenzo175** [comment]
Here are the current file sizes with the current level of compression:

| model |GFS 0.25 degree | NAM 12km | RAP | HRRR hourly | HRRR subhourly | Total |
|--|--|--|--|--|--|--|
| Size per file  | 17 MB | 27 MB  | 7 or 12 MB | ~160 - 330 MB | 450 - 600 MB |  |
| Size per day | 66 MB | 107 MB|  173 MB | ~ 4.7 GB | 13 GB | 18 GB |
| Size per year| 23 GB | 38 GB  | 62 GB |  1.7 TB | 4.6 TB | 6.4 TB |
