### ISSUE TITLE
Add deterministic metric functions (standalone)

### ISSUE THREAD

**Issue by dplarson** [SolarArbiter/solarforecastarbiter-core#114]
Add functions for computing deterministic forecast evaluation metrics, all of which are standalone functions (i.e. they only require as input the measured and predicted time-series, and do not perform any pre-processing of the data). In other words, these are the lowest level functions for computing the metrics, with the assumption that higher-level functions would call the functions as needed (e.g. after aligning and resampling time-series).

Current list of deterministic metrics:
- [ ] mean absolute error (MAE)
- [ ] mean bias error (MBE)
- [ ] mean absolute percentage error (MAPE)
- [ ] root mean square error (RMSE)
- [ ] normalized RMSE (nRMSE)
- [ ] centered (unbiased) RMSE (cRMSE)
- [ ] Pearson correlation coefficient (r)
- [ ] coefficient of determination (R^2)
- [ ] Kolmogorov-Smirnov Integral (KSI)
- [ ] the OVER metric (OVER)
- [ ] forecast skill (s)
- [ ] combined performance index (CPI)

Notes:
- this issue is related to #4 
- a separate issue will be opened for tracking the probabilistic forecast metrics
- other metrics may be added later

**Comment by dplarson** [comment]
@wholmgren @alorenzo175 @lboeman I can't assign the issue to myself, but the point of me adding this issue is so that I can track my work on adding these functions (which I'll contribute via a MR once ready).

**Comment by wholmgren** [comment]
@dplarson I don't typically use the assign issues feature but we can if that's helpful. Do you prefer that we assign issues to for you? @awig?

**Comment by dplarson** [comment]
@wholmgren In that case, no need to assign the issue. (I just wanted to make it clear I'll be working on this, to avoid duplication, and I'm use to using assigning as a way to track whose working on what.)
