### ISSUE TITLE
metrics: MAPE definition

### ISSUE THREAD

**Issue by dplarson** [SolarArbiter/solarforecastarbiter-core#118]
While reviewing the metrics proposal document (https://solarforecastarbiter.org/metrics/), I noticed the mean absolute percentage error (MAPE) definition is not standard (or at least, it's not the definition I'm use to):

- current definition: `MAPE = MAE / norm = 1/n * sum_{i=1}^n |F_i - O_i|`
- standard definition: `MAPE = 1/n * sum_{i=1}^n |(F_i - O_i) / O_i|`

where `F_i` is a forecast, `O_i` is an observation, and `norm` is some reference value (e.g. the nameplate capacity of a PV system).

The current definition seems more like a normalized MAE, rather than MAPE. I suggest we use the standard definition (as described above).

@wholmgren Thoughts?

**Comment by wholmgren** [comment]
I think we want to encourage or require the formula in the "current definition" so we avoid issues as `O_i --> 0`. Sure we can filter by zenith angle or observed value, but I'd rather play it safe in most scenarios. I'm not entirely opposed to implementing what you've called the "standard definition" in addition to the current definition.

I'm ok calling it either NMAE or MAPE, though at this moment I'd lean towards NMAE. I don't know that there is a right answer for terminology.

I recall @cwhanse had some comments on this in the metrics proposal to the stakeholders.

**Comment by cwhanse** [comment]
MAPE should be an average of errors in percent, the 'standard definition' @dplarson writes.  NMAE is the 'current definition', the normalized MAE.  They are different, in my mind, and it's not either/or: there's room for both.  The requirement is to be absolutely clear about what is calculated.

**Comment by dplarson** [comment]
Thanks for the feedback. As part of adding deterministic forecast metrics, I'll plan to implement both MAPE (using the "standard" definition I listed above) and NMAE in the metrics code.

**Comment by wholmgren** [comment]
Did we decide at some point to only support NRMSE? I think we may have discussed it but I can't recall an outcome. If so, this issue can be closed now. If not, this issue can be closed by adding NMAE.

**Comment by dplarson** [comment]
@wholmgren I don't recall an explicit discussion about only supporting NMRSE and I think it's probably worthwhile to support computing NMAE, NMBE and NRMSE. But it brings up a related question: would it be better to a) have separate functions for NMAE, NMBE and NRMSE or b) add a kwarg to the MAE, MBE and RMSE functions to enable computing the normalized versions.

Example:

```python
def mean_absolute(obs, fx, norm=None):
    """Mean absolute error (MAE).

        MAE = 1/n sum_{i=1}^n |fx_i - obs_i|

    Parameters
    ----------
    obs : (n,) array-like
        Observed values.
    fx : (n,) array-like
        Forecasted values.
    norm : float
       Normalized factor, in the same units as obs and fx.

    Returns
    -------
    mae : float
        The MAE of the forecast.

    """

    mae = np.mean(np.abs(fx - obs))
    if norm:
        return mae / norm
    else:
        return mae
```

**Comment by wholmgren** [comment]
What would fit best with the approach in #224?

**Comment by dplarson** [comment]
Probably separate functions for each of the normalized metrics (MAE, MBE, RMSE).
