### ISSUE TITLE
make a contributing guide

### ISSUE THREAD

**Issue by alorenzo175** [SolarArbiter/solarforecastarbiter-core#13]
Perhaps as a series of wiki pages including:
- list of standard nomenclature
- code style guidelines 
- policy on exceptions
- policy on logging
- when arguments may be expected to be a DataFrame vs Series
- PR review policy/template if needed

**Comment by wholmgren** [comment]
work in progress here:

- wikis: https://github.com/SolarArbiter/solarforecastarbiter-core/wiki
- docs: https://solarforecastarbiter-core.readthedocs.io/en/latest/contributing.html
