### ISSUE TITLE
validator - add limit checking for irradiance, temperature, wind

### ISSUE THREAD

**Issue by cwhanse** [SolarArbiter/solarforecastarbiter-core#15]

**Comment by wholmgren** [comment]
Reading [Ohm98 Baseline Surface Radiation Network (BSRN-WCRP) New Precision Radiometry for Climate Research.pdf](https://github.com/SolarArbiter/solarforecastarbiter-core/files/2903076/Ohm98.Baseline.Surface.Radiation.Network.BSRN-WCRP.New.Precision.Radiometry.for.Climate.Research.pdf) for background on uncertainty issues. Table 5 is relevant to this issue.

Direct solar irradiance: Direct solar irradiance with transmission coefficient of 0.9
Diffuse sky irradiance: 700 W m~2, the largest value ever recorded
Global irradiance 2: TOA irradiance for solar zenith angle (z)less than 80°; TOA irradiance + 0.56(z - 93.9)2 for z larger than 80°; upper bound of global irradiance when the sun is near the horizon

Not saying these should be our limits, but maybe something to point to.

**Comment by cwhanse** [comment]
This one also: ftp://ftp.cmdl.noaa.gov/g-rad/isis/qcrad_v3/Long_TOAtmosJ.pdf.  This paper is the primary reference for QCRad, which is what NOAA applies to the SURFRAD data.  I have the Fortran code and documents for QCRad, either Chuck Long sent it or pointed me at a download, I don't recall which.

**Comment by wholmgren** [comment]
ftp://aftp.cmdl.noaa.gov/data/radiation/QCRad_RadFlux_Workshop/Codes/QCRad/

**Comment by wholmgren** [comment]
closed by #29
