### ISSUE TITLE
report metrics should downloable in csv format

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-core#160]
Basically want to make csv versions of the tables and graphs that are downloadable when you click an icon or text.

**Comment by wholmgren** [comment]
Appears to be non-trivial to get the data from bokeh and into a csv. Maybe it should be a link going back to the database anyways. In any case, not going to happen for initial beta.

**Comment by alorenzo175** [comment]
Should be possible to pull the data directly from the plots w/ javascript. See https://github.com/bokeh/bokeh/tree/master/examples/app/export_csv

**Comment by wholmgren** [comment]
That doesn't seem so bad after all. It looks easy enough that I am concerned about why bokeh doesn't directly support it.

**Comment by alorenzo175** [comment]
closed in #321
