### ISSUE TITLE
account for timezone in metrics/report generation

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-core#164]
metrics grouped by time, especially daily and hourly, need to account for timezone. Most straightforward would be to use the site's timezone.

For example, here's an hourly metrics figure for the OASIS site that specified as GMT/Etc+7:

<img width="828" alt="Screen Shot 2019-08-27 at 4 40 30 PM" src="https://user-images.githubusercontent.com/4383303/63815577-fe3f3080-c8e9-11e9-8a9f-0d5e173d1b3f.png">

Most users would probably prefer the metrics reported in local time and thus in this case roughly centered on solar noon.

**Comment by wholmgren** [comment]
This is easy enough for the metrics graphs, but harder to do for the time series. Bokeh converts tz-aware times into tz-naive UTC times. I think the only solution is to convert the tz-aware times into tz-naive times in the desired time zone. Easy enough if done within any given plot function, but the reports currently use the `construct_fx_obs_cds` to create a common `ColumnDataSource` for linked plots. That means that we'd be passing around naive, non-UTC times, which requires some care.

Know of any other solution @alorenzo175?

**Comment by wholmgren** [comment]
I see ADVI uses the `tz_convert('MST').tz_localize(None)` [approach](https://github.com/UARENForecasting/advi/blob/883b3c7e68a415902dec64523e44908b549f9938/app/main.py#L547-L554)

**Comment by alorenzo175** [comment]
It does, not ideal, but perhaps best for now. Better would be to help implement https://github.com/bokeh/bokeh/issues/1135 for support in Bokeh
