### ISSUE TITLE
improve report package version section

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-core#165]
Currently looks a bit junky. Maybe should be better organized. Maybe something that needs to be fixed here (like with a class or div), maybe also a dashboard issue. @lboeman ?

<img width="754" alt="Screen Shot 2019-08-27 at 4 50 23 PM" src="https://user-images.githubusercontent.com/4383303/63815812-d7352e80-c8ea-11e9-8b40-7c9469faeefa.png">

**Comment by alorenzo175** [comment]
Seems like this is fixed?

**Comment by wholmgren** [comment]
Left it open because we might need to make some modifications as the dashboard is updated. It's currently just a bare table and it might need an id or something.

**Comment by wholmgren** [comment]
On second thought, good enough for now. I'm sure we'll make changes to this once the full metrics are available and the report template undergoes major changes.
