### ISSUE TITLE
Create more formal map of climate zones

### ISSUE THREAD

**Issue by dplarson** [SolarArbiter/solarforecastarbiter-core#170]
Create a more formal version of the climate zones map, likely through the use of GIS tools (e.g. a shapefile that contains the climate zones as polygons). The initial goal is a map figure with more refined outlines of each zone (using the current map figure as the starting point), while future work can focus on things like formal definitions of the zones and computing the zone given a lat-lon coordinate.

**Comment by dplarson** [comment]
@wholmgren Note: I'm opening this issue here, but let me know if it's better to open an issue (and later a PR) against the website since that's where the current map figure exists.

**Comment by wholmgren** [comment]
Did you see #153? Perhaps a duplicate unless I'm misunderstanding a distinction.

**Comment by dplarson** [comment]
Somewhat of a duplicate of #153, although I meant this issue to focus solely on the visualization portion (i.e. create a shapefile with refined outlines of the zones) as a first step.

**Comment by wholmgren** [comment]
Ah, ok. #153 should probably be moved to `solarforecastarbiter-api` and this one to either `solarforecastarbiter_dashboard` or `solararbiter.github.io`. @lboeman @alorenzo175 ?

**Comment by lboeman** [comment]
Agreed. If we're not tracking any code for the production of the climate zone shapefile and just want a reminder/place for discussion, it should live in `solararbiter.github.io`. Unless we're trying to have some interactive visualization?

**Comment by wholmgren** [comment]
In the long run we would like to have a map of at least reference data sites (and possibly any site a user has access to) with a climate zone layer. Certainly a dashboard thing if including user sites. Probably also helpful to have a simple map of the climate zones that lives on the static page. Reference data plus climate zones could probably live in either repo.

**Comment by dplarson** [comment]
Thanks for the feedback. I'll move this issue over to `solararbiter.github.io` to focus on adding a revised version of the (static) climate zone map to the website (although the results can probably be a starting point for future revisions, e.g., adding the climate zones onto an interactive map showing the reference data sites).
