### ISSUE TITLE
validator - detect clear sky periods

### ISSUE THREAD

**Issue by cwhanse** [SolarArbiter/solarforecastarbiter-core#19]

**Comment by wholmgren** [comment]
@cwhanse I'm assuming we're going to use the pvlib implementation of Reno & Hansen for this feature. Do you have any thoughts on how it should work for different combinations of interval length (1 minute to 60 minutes) and interval label (beginning/ending vs. instantaneous)? Perhaps we could update the pvlib `detect_clearsky` function documentation with a table of recommended kwargs.

For 1.0 alpha, I'd like to see at least a basic implementation of this feature that covers ~1 minute frequency irradiance data. ~Hourly and/or power data could come later. 

Do you want to take this on or should I put it on my to do list?

**Comment by cwhanse** [comment]
I thought we'd use Reno.  We can implement for GHI and use the default parameters for 1-3 minute intervals, 10 samples per interval.  I think we could extend the parameter sets to longer time averages (15m would be nice).  For 60min data, I don't think Reno will work, if this is important I'd look at Bennet's quantile regression method. 

For POA irradiance and power, we'd need to recode the Reno algorithm to work with a clearsky POA / power model.  In these cases maybe Bennet would work, worth looking at.

If the few-minute GHI function is waiting on me, it won't get done until week after next.

Two papers recently of relevance:
- Ellis et al 2018: https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8547877&tag=1 (there's also a journal article in preparation, I understand): essentially a validation of the original Reno algorithm. They provide parameters for longer time intervals, but in their work the data are subsampled on the longer time steps, not averaged over the intervals.  I'd guess the subsample case is not common.  For this reason I am hesitant to use their parameter values.

- Gueymard et al 2019: https://www.researchgate.net/publication/332565089_A_posteriori_clear-sky_identification_methods_in_solar_irradiance_time_series_Review_and_preliminary_validation_using_sky_imagers  A rather thorough comparison of methods to determine clear-sky conditions and cloudless sky conditions from ground data.  They consider methods which require more than GHI, and not surprisingly, if DNI or DHI are available the methods are better.  Still have this set aside for a careful read, but first glance through, Reno is as good as any of the GHI-only methods.
