### ISSUE TITLE
probabilistic forecasts from observations

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-core#195]
some options include:

* persistence ensemble (most recent N observations at same time of day)
* raw persistence ensemble (most recent N observations)
* complete history persistence ensemble (all observations at same time of day)
* climatology (all observations)

**Comment by cwhanse** [comment]
Relevant to our phone discussion about computing percentiles, I recommend we stick with `numpy.percentile` with the default `interpolation=linear`. This method is the default in R's quantile function and is intuitive (connect points on the CDF with straight line segments and interpolate). Alternatives have been discussed at length for numpy e.g. [here](https://github.com/numpy/numpy/issues/10736) with no consensus for the need to change the default.

**Comment by wholmgren** [comment]
also relevant to #115

**Comment by wholmgren** [comment]
@dplarson just wanted to make sure you saw @cwhanse's comment/link above

**Comment by dplarson** [comment]
Per today's team discussion, I'll take lead on adding reference probabilistic forecasts. My hope is to open a draft PR by next week to outline my general approach and get feedback before I dive into the coding details.
