### ISSUE TITLE
validator - add clear sky power model

### ISSUE THREAD

**Issue by cwhanse** [SolarArbiter/solarforecastarbiter-core#20]

**Comment by cwhanse** [comment]
@wholmgren this function will take in system and model metadata and a DatetimeIndex, and give back clearsky power.  It's a wrapper around `pvmodel.calculate_solar_position`, `pvmodel.calculate_clearsky` and `pvmodel.irradiance_to_power`.  I think a separate function is a good idea, because the calculation is likely to be needed in several places.

Would you like the function in `pvmodel`?  That would be my choice.

**Comment by wholmgren** [comment]
If you're going to wrap all of those functions I think you'd want to take in a [datamodel.SolarPowerPlant](https://solarforecastarbiter-core.readthedocs.io/en/latest/generated/solarforecastarbiter.datamodel.SolarPowerPlant.html#solarforecastarbiter.datamodel.SolarPowerPlant) and DatetimeIndex.

I am ok with this as a convenience function in principal. I worry about unnecessary recalculations of solar position in practice. I don't have a good sense of the whole workflow yet, though, so maybe I am off base here. Two potential wrappers that might make it more clear what I'm thinking about...

```python
def validator_wrapper_efficient(power_plant):
    solar_position = pvmodel.calculate_solar_position(*power_plant_args)
    validator.test1(solar_position, etc)
    validator.test2(solar_position, etc)
    validator.test3(solar_position, etc)


def validator_wrapper_inefficient():
    validator.test1(power_plant, etc)  # calls calc solar position
    validator.test2(power_plant, etc)  # calls calc solar position
    validator.test3(power_plant, etc)  # calls calc solar position
```

**Comment by cwhanse** [comment]
I'll hold off on this function for now. I'm aiming at #22 next, which can be written to expect `Series` of clear sky power instead of calculating that internally.

**Comment by wholmgren** [comment]
Sounds good to me.

**Comment by cwhanse** [comment]
I think we can close this issue.  Functions are in `pvmodel.py` to calculate clearsky irradiance and to translate irradiance to power.

**Comment by wholmgren** [comment]
agree.
