### ISSUE TITLE
metrics table has insufficent sig figs for kW sized systems

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-core#206]
e.g. for Cocoa RTC

<img width="670" alt="Screen Shot 2019-10-03 at 7 57 55 PM" src="https://user-images.githubusercontent.com/4383303/66177892-253eff80-e618-11e9-8eb9-a520caa599d5.png">

probably want some code to automatically determine number of digits based on system size.

**Comment by wholmgren** [comment]
Wait for bokeh 2.0 https://github.com/bokeh/bokeh/pull/9319

**Comment by alorenzo175** [comment]
no more bokeh tables as of #321
