### ISSUE TITLE
Enforce interval length in reference data uploads

### ISSUE THREAD

**Issue by alorenzo175** [SolarArbiter/solarforecastarbiter-core#209]
Looks like CRN may provide uneven data. We should enforce the interval length and go back and make sure all the old data is also consistent.

**Comment by alorenzo175** [comment]
CRN, RTC data sometimes have missing values.  I think, for now, we should trust the current reference data has been appropriately resampled for the interval type and just make sure nans are present in the upload.

**Comment by wholmgren** [comment]
agree
