### ISSUE TITLE
automated reports for selection of reference data sites

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-core#222]
We could set up a task to automate the generation of reports for a selection of the reference data and forecast sets. The reports would be publicly available under the reference organization. We might want to delete the old report once the new one is created since we've not yet though through if/how reports can be updated.

**Comment by alorenzo175** [comment]
Which sites do you want automated reports for? SURFRAD + SOLRAD + RTC? GHI, DNI, power?

**Comment by alorenzo175** [comment]
Right now, there are reports being automatically updated by the job framework here https://dev-dashboard.solarforecastarbiter.org/reports/

We can do the same for these automated reports, although right now the report parameters (like start/end) do not change.

**Comment by wholmgren** [comment]
> SURFRAD + SOLRAD + RTC? GHI, DNI, power?

That set seems reasonable. Can we add MIDC or at least OASIS?

**Comment by wholmgren** [comment]
will this be closed in beta4?

**Comment by alorenzo175** [comment]
The code to make the automatic reports is there, but I wanted to automate the creation of the reports. I don't think that is super useful at the moment, so I'll probably just check in a script that can make the reports and start the jobs.

So yes, this should be done with beta4.
