### ISSUE TITLE
Add summary stat functions for observations and forecasts

### ISSUE THREAD

**Issue by dplarson** [SolarArbiter/solarforecastarbiter-core#231]
Add functions (probably to the Metrics module) that cover commonly requested summary statistics of the observations and forecasts, e.g., min, max, mean and standard deviation.

This issue is in response to discussion from #230 (quoted below for ease of reference):

> Maybe a new issue, but we could expand the scope of this PR: should we also add functions for statistics of the observations/forecasts? Maybe just mean and std dev for now. I think our functions would just return the numpy operations, but it would formalize their availability in our package. In either case, I'd like to eventually present those statistics in the reports so it will need to be calculated somewhere.

**Comment by dplarson** [comment]
@wholmgren Any preference on where to place this code (e.g. `solarforecastarbiter.metrics.summary.<function>` vs `solarforecastarbiter.metrics.<function>`)? And thoughts on a combined summary statistics function vs separate functions (e.g. `results = summary_stats(obs, fx)` vs `obs_mean = mean(obs)`; `obs_std = std(obs)`, etc.)?

If no preference, I would suggest 1) keeping all code in the metrics root (i.e. `solarforecastarbiter.metrics.<function>`, not `solarforecastarbiter.metrics.summary.<function>`) and 2) a single summary function instead of separate functions (e.g. `results = summary_stats(obs, fx)`).

**Comment by wholmgren** [comment]
Same consideration as for the normalized metrics... what's going to make the most sense when integrating with the rest of the workflow (specifying which metrics to calculate, calculating, injecting into a report)? These summary statistics might be presented differently than error metrics, so things could be different.

**Comment by dplarson** [comment]
In terms of integration, I think separate functions (e.g. `mean()`, `std()`) make the most sense for the scenario where the "user" selects some subset (or all) of the summary statistics to show in the report.

I'll move forward in this direction and have a PR open shortly.
