### ISSUE TITLE
report CLI fxobs ordering reversed

### ISSUE THREAD

**Issue by alorenzo175** [SolarArbiter/solarforecastarbiter-core#236]
compare https://github.com/SolarArbiter/solarforecastarbiter-core/blob/1e0d2d4f494c5819635cbed101739515726341aa/solarforecastarbiter/cli.py#L311-L312
to 
https://github.com/SolarArbiter/solarforecastarbiter-core/blob/1e0d2d4f494c5819635cbed101739515726341aa/solarforecastarbiter/io/api.py#L588-L591

**Comment by wholmgren** [comment]
🤦‍♂ 

are you fixing this in a current PR?

**Comment by alorenzo175** [comment]
I can, although I was going to leave it for another PR with the report signature
