### ISSUE TITLE
report timeseries observation handling

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-core#237]
`reports.figures.timeseries` contains logic to shade the observation time series according to its `interval_length` and logic to control the step based on `interval_label`. The problem is that the function gets the original observation instead of processed observation metadata.

`report.render_raw_report` creates `fx_obs_cds`, a list of tuples `(RawReport.processed_forecasts_observations.original, ColumnDataSource)`.

Probably need to change that to be the whole `RawReport.processed_forecasts_observations` object.

**Comment by alorenzo175** [comment]
duplicate of #238?

**Comment by wholmgren** [comment]
Yep. I got a 500 error from github the first time that I tried to create this issue.
