### ISSUE TITLE
Add cost metric

### ISSUE THREAD

**Issue by dplarson** [SolarArbiter/solarforecastarbiter-core#258]
Add cost metric(s) to the `metrics` subpackage. Can focus first on the "simple" case where a user provides a cost per error value (e.g. `$/MW`), either a single value or a (potentiall) time-series corresponding to the forecasts/observations.

**Comment by wholmgren** [comment]
Let's let this issue stand for the simple case here in core, but will link to #126 and some related discussion in the api repo: https://github.com/SolarArbiter/solarforecastarbiter-api/issues/157
