### ISSUE TITLE
Metrics: input naming and order conventions

### ISSUE THREAD

**Issue by dplarson** [SolarArbiter/solarforecastarbiter-core#262]
While implementing the deterministic and probabilistic forecast metrics, I forgot to ensure that the function inputs following the same conventions regarding names and ordering of inputs. While the conventions within each type (deterministic and probabilistic) are consistent, they are not the same between the two:
- names:
   - deterministic: `y_true` (observations), `y_pred` (forecasts)
   - probabilistic: `obs` (observations), `fx` (forecasts)
- input order:
   - deterministic: observations, forecasts
   - probabilistic: forecasts, observations

For consistency, we should revise the metrics code to use a more consistent naming and ordering convention for the inputs.

**Comment by dplarson** [comment]
Based on other parts of the codebase, I suggest we standardize on `obs` and `fx` for observations and forecasts. I'm less sure on input ordering, but I would lean towards (observations, forecasts) since all metrics depend on observations, but some depend on additional inputs related to the forecasts (e.g. `obs, fx`, `obs, fx, fx_prob`, `obs, fx, ref`).

**Comment by wholmgren** [comment]
Good catch. I agree with your suggestions. Let’s double check with @alorenzo175

**Comment by alorenzo175** [comment]
I also agree with your suggestions.

**Comment by dplarson** [comment]
Great! I'll open a PR to standardize the inputs once #250 is merged.
