### ISSUE TITLE
Metrics: default to normalizing by max observation?

### ISSUE THREAD

**Issue by dplarson** [SolarArbiter/solarforecastarbiter-core#269]
For normalized metrics (specifically NMAE, NMBE, NMRSE), does it make sense to support both a) user-supplied normalizing factors (current approach) and b) a default method for computing the normalizing factor (e.g. max observation value)? From a coding standpoint, this would change, e.g., `normalized_mean_absolute(obs, fx, norm)` to `normalized_mean_absolute(obs, fx, norm=None)` (i.e. change `norm` to a kwarg and add an if/else statement for switching between normalizing by a user-supplied value or a default).

If we agree to also supporting a default method for normalization, should we stick with using the max observation or something else (e.g. mean)? From my experience, normalizing by the max observation is more common, but I'm open to discussions.

**Comment by wholmgren** [comment]
The data model for PV plant specifications requires `dc_capacity` and `ac_capacity`. I'd use those numbers. Normalization for irradiance is most likely to be done with time dependent clear sky index, but we could consider a fixed number like 1000 W/m^2 too.

Using that kind of metadata would mean the metrics functions would remain the same but the calling function would need to get and provide data from elsewhere.

I'm hesitant to rely on the max observation value given the likely poor quality of some incoming data.

**Comment by dplarson** [comment]
That makes. In that case, I agree with keeping the metric functions the same and then having the calling function pull the necessary data from elsewhere. Therefore, I'll go ahead and close this issue.
