### ISSUE TITLE
revisit reports metrics and category specifications

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-core#273]
As discussed in PR #224 [comment](https://github.com/SolarArbiter/solarforecastarbiter-core/pull/224/files/47de0bcaeb8b2c29562255cfae4de5ceec3f220a#r350451270), we should reconsider how we want to specify the metrics and the categories in the report metadata. 

1. `'Root mean squared error'` and `'Month of the year'`
2. `'rmse'` and `'month'`

currently metrics section follows 2 and categories follows 1. I think we should be consistent, and I have a preference for option 2 because it avoids easy to mess up things like capitalization and spaces.

**Comment by dplarson** [comment]
I'm also in favor of option 2 (lowercase and single word).

**Comment by wholmgren** [comment]
Thanks. Tony and Leland agree too so I'll go ahead and revise.
