### ISSUE TITLE
metrics determistic._MAP missing some entries, none in probabilistic

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-core#275]
@awig @dplarson can you guys make sure the `_MAP`, `_REQ_REF_FX`, and `_REQ_NORM` are correct for the metrics modules? I think they got out of sync while @awig was working on #224 and @dplarson was working on a handful of metrics implementations.

**Comment by dplarson** [comment]
Sure, I'll check now and submit a PR to fix any issues I find.
