### ISSUE TITLE
metrics: track why data is dropped (e.g. NaNs)

### ISSUE THREAD

**Issue by dplarson** [SolarArbiter/solarforecastarbiter-core#290]
As discussed in #285 and #288, there is (likely) a need to track why data is dropped (observations or forecasts) during the metrics pre-processing step and then reported back, e.g., in the reports. The simplest case is just summarizing the things done (e.g. "dropped NaNs from observations"), but we may want to track in a more fine-grain resolution (e.g. a time-series that shows the exact timestamps where data was removed).

**Comment by alorenzo175** [comment]
closed in #321 at least coarsly
