### ISSUE TITLE
Add NIGHTTIME validation for power variables

### ISSUE THREAD

**Issue by alorenzo175** [SolarArbiter/solarforecastarbiter-core#293]

**Comment by wholmgren** [comment]
The irradiance NIGHTTIME validation is ultimately performed by `check_irradiance_day_night`

https://github.com/SolarArbiter/solarforecastarbiter-core/blob/4f3591b98e2f91d5bf50495bd484dbc63adfbf6b/solarforecastarbiter/validation/validator.py#L449-L465

but there is no reason why this function can't be applied to power, too. Is it as simple as adding to `validate_daily_ac_power` and `validate_daily_dc_power`?

https://github.com/SolarArbiter/solarforecastarbiter-core/blob/4f3591b98e2f91d5bf50495bd484dbc63adfbf6b/solarforecastarbiter/validation/tasks.py#L310-L336

I'd also add to temperature, wind, and rh for consistency in evaluations.
