### ISSUE TITLE
Group by categories: use local timezone, not UTC

### ISSUE THREAD

**Issue by dplarson** [SolarArbiter/solarforecastarbiter-core#298]
Related to #234 and discussions in #297: we should ensure that the `groupby` categories in the `metrics.calculator` use the local timezone, not UTC (e.g. `groupby` hour of the day).

There may be some questions about specifics and edge cases, but in general, grouping by the local timezone is what most users will expect.

**Comment by awig** [comment]
@dplarson to clarify, do you mean the local timezone as given by the `ReportMetaData` to which the pandas.DataFrame should be made tz aware? I thought the dataframes/series were being made tz aware before any groupby occurs.

**Comment by dplarson** [comment]
While the dataframes/series are tz aware, this issue was meant to confirm that groupby respects the tz. (It probably does, but I'm not 100% sure yet.)

**Comment by dplarson** [comment]
Based on today's discussion, the consensus is to display the metrics categories (e.g. hour of day) using the timezone from the report, not the individual sites. For example, a report in Pacific time for all seven SURFRAD sites would show the metrics in Pacific time, not the timezone of each site.

**Comment by dplarson** [comment]
Notes to myself:
- in `datamodel.py`: the dataclass `ReportMetadata` (defined in `datamodel.py`) stores a `timezone` attribute
- in `reports/main.py`: `create_metadata()` sets `ReportMetadata.timezone` via `infer_timezone()`
- in `reports/main.py`:`create_rawreport_from_data()` calls `validate_resample_align()`, which in turn calls `metrics.preprocessing.resample_and_align()` with the timezone from the report
- in `metrics/preprocess.py`: `resample_and_align()` seems to already do a timezone conversion using the timezone from the report

Based on the above, there probably is not a need for code revisions to any of the report or metrics code in order to resolve this issue. Instead, we may just need a few tests to explicitly check that the reported metrics behave as expected (e.g. if the report timezone is not the same as the site timezone).

**Comment by dplarson** [comment]
With PR #314 merged, this issue can be marked as complete and closed.
