### ISSUE TITLE
add integrations for testing, documentation, linting

### ISSUE THREAD

**Issue by alorenzo175** [SolarArbiter/solarforecastarbiter-core#3]
Probably want the following integrations:
- [x] travis-ci
- [x] appveyor
- [x] coveralls
- [x] readthedocs
- [x] lgtm
- [x] something for flake8?

**Comment by alorenzo175** [comment]
In terms of CI/testing what should we use? Options include travis (full VM, ubuntu), appveyor (VM, windows, linux), circle-ci (container, linux, mac), azure pipelines (container or vm, windows, linux, mac). 

This package will primarily run in linux containers, so maybe start there.

**Comment by wholmgren** [comment]
I heard someone say good things about azure pipelines somewhere. Travis is well known and dependable. Appveyor is annoying in pvlib. 

I prefer codecov to coveralls, but not strongly.

I've been happy enough with stickler for flake8 in pvlib.

**Comment by cwhanse** [comment]
I have `test_validator.py` started, uses pytest, if you can show me where to put it.

**Comment by wholmgren** [comment]
in a `tests` directory inside the `validation` directory. So full path is `solarforecastarbiter/validation/tests/test_validator.py`. See the `io` subpackage for example: https://github.com/SolarArbiter/solarforecastarbiter-core/tree/master/solarforecastarbiter/io/tests
