### ISSUE TITLE
Typo in validation.quality_mapping.check_if_series_flagged

### ISSUE THREAD

**Issue by awig** [SolarArbiter/solarforecastarbiter-core#304]
@cwhanse 

I was reviewing the quality_mapping functions and I noticed what I believe is a typo with the double negative on 
[`raise ValueError('Not all data has not been validated')`](https://github.com/SolarArbiter/solarforecastarbiter-core/blob/5fbbd17938d45f743d25205d8a4669000cb10292/solarforecastarbiter/validation/quality_mapping.py#L304)
but thought I would check first.  If so, I can go head and fix it on my branch for my next PR.

**Comment by cwhanse** [comment]
@alorenzo175  can confirm, I think that message should be the same as [this](https://github.com/SolarArbiter/solarforecastarbiter-core/blob/5fbbd17938d45f743d25205d8a4669000cb10292/solarforecastarbiter/validation/quality_mapping.py#L200)

**Comment by alorenzo175** [comment]
Yes, I agree with Cliff.

**Comment by awig** [comment]
Okay. Thanks unless someone else incorporates it. I'll make the change on my working branch.

**Comment by alorenzo175** [comment]
closed in #321
