### ISSUE TITLE
metrics: calculator: support probabilistic forecasts

### ISSUE THREAD

**Issue by dplarson** [SolarArbiter/solarforecastarbiter-core#315]
Related to #266: `metrics.calculator` needs to be revised to support probabilistic forecasts. (Currently only deterministic forecasts are supported, but the framework is there to extend to probabilistic forecasts.)

**Comment by awig** [comment]
TODO: for `calculator.py`

- [x] create probabilistic forecast related pytest fixtures in conftest and test_calculator
- [x] add support for `ProbabilisticForecast` in `calculate_metrics`
   - [ ] TEST - `test_calculate_metrics_with_probabilistic`
- [x] add `calculate_probabilistic_metrics`
   - [ ] TEST - `test_calculate_probabilistic_metrics_no_metrics`
   - [ ] TEST - `test_calculate_probabilistic_metrics_no_reference`
   - [ ] TEST - `test_calculate_probabilistic_metrics_no_reference_data`
   - [ ] TEST - `test_calculate_probabilistic_metrics_no_all_forecasts`
   - [ ] TEST - `test_calculate_probabilistic_metrics_no_all_forecasts_data`
   - [ ] TEST - `test_calculate_probabilistic_metrics_reference`
   - [ ] TEST - `test_calculate_probabilistic_metrics_all_forecasts`
   - [ ] TEST - `test_calculate_probabilistic_metrics`
- [x] add `_apply_probablistic_metric_func`
   - [ ] TEST - `test_apply_probabilistic_metric_func`
   - [ ] TEST - `test_apply_probabilistic_bad_metric_func`
