### ISSUE TITLE
Allow one to specify report timezone instead of always inferring

### ISSUE THREAD

**Issue by alorenzo175** [SolarArbiter/solarforecastarbiter-core#317]

**Comment by wholmgren** [comment]
TA2/3 evaluations need this or we need to change the time zone of the reference sites to the relevant Etc/GMT zone. I think I'd prefer to knock this out. Probably straightforward except for ensuring API compatibility with existing reports.

**Comment by wholmgren** [comment]
Unburying the referenced comment in #321. Comment on 

https://github.com/SolarArbiter/solarforecastarbiter-core/pull/321/files/9d10bb53ec3cc3bd5ded1b372a71cc9318623fe6#diff-4c1ac92797e5bac8fe5c8d2f9eb9a935ef821b4305a5dd477c1720d17c28b3af

in `reports/main.py` line 

```python
timezone = infer_timezone(report_params)
```

>  @wholmgren wholmgren on Feb 3, 2020 Member
> thinking ahead on api changes and guessing we'll move this to kwarg to address #317
> @alorenzo175 alorenzo175 on Feb 3, 2020 Author Member
> it would probably be a part of report parameters, so we can probably let infer choose the right thing
