### ISSUE TITLE
change units of temperature coefficient from 1/C to %/C

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-core#350]
The temperature coefficient is currently specified in units of 1/C, so users input values like -0.003. This would be fine on its own, but we also have DC and AC loss factors that are specified in units of %. 

This was brought up by someone at the DOE review meeting in October but we forgot to create an issue for it. If I recall correctly, @cwhanse agreed that this should be changed. 

Probably now or never on this.

**Comment by cwhanse** [comment]
Agree it would be better as %/C, that's the unit found on datasheets.

**Comment by wholmgren** [comment]
@alorenzo175 how should we handle this? I think we'd need to update any user-supplied metadata that exists.

**Comment by alorenzo175** [comment]
Updating the core/dashboard to specify it as %/C and updating the user supplied value at the same time is probably the way to go. We could do the database update as part of a migration, or notify any orgs that have sites with it set to update it (once updating via the dashboard works).

**Comment by wholmgren** [comment]
> or notify any orgs that have sites with it set to update it (once updating via the dashboard works).

I'm ok with this given the very few people this would effect and the fact that any early adopters are likely to be more tolerant of this sort of thing.
