### ISSUE TITLE
Event observation and forecast dataclasses

### ISSUE THREAD

**Issue by dplarson** [SolarArbiter/solarforecastarbiter-core#357]
PR #348 added standalone functions for computing event forecast metrics, but didn't include anything about the dataclasses for the event observations and forecasts, which are prerequisites (corequisites?) for integrating the event metrics into the report module. Hence this issue.

The part I'm struggling with is whether to require the input event obs/fx time-series to be provided as a) `timestamp,boolean` (e.g. `2020-03-03 00:00,True \n 2020-03-03 01:00,False` = event occurred at 00:00, but not at 01:00) or b) `timestamp_start,timestamp_end` (e.g. `2020-03-03 00:00,2020-03-03 02:15` = event occurred from 00:00 through 02:15). Either way, I expect the obs/fx data will be transformed into a time-series similar to option a) (`timestamp,boolean`) for computing the metrics and visualization.

If I had to pick, I would lean towards option a) (`timestamp,boolean`) as it's more similar to the deterministic forecast and observation datamodel, and therefore likely requires less revisions/code to integrate.

@wholmgren @alorenzo175 @awig Thoughts? If no one has strong opinions, I'll just move forward with option a) (`timestamp,boolean`).

**Comment by wholmgren** [comment]
Forecasts and observations must be uploaded like A, so I’d go that route.

**Comment by dplarson** [comment]
> Forecasts and observations must be uploaded like A, so I’d go that route.

Great. That solves that.
