### ISSUE TITLE
Account for uncertainty using dead bands

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-core#358]
Basic idea is 

```python
# deadband is a value between 0 and 100% (0 and 1 absolute)
error = fx - obs
# use obs to avoid potential for gaming with forecasts
mask = error <= deadband * obs
error[mask] = 0
```

I had been worried about divide by 0 errors but @alorenzo175 convinced me it wasn't so complicated.

The report interface could include a checkbox and/or field where users input the dead band as a % of observation value. Could default to the uncertainty of the observation.

We could also consider implementing dead bands for absolute errors (e.g. 1 MW). I think we should focus on the % approach for now, though.

**Comment by wholmgren** [comment]
Implementation questions.

Question 1: How do we get `deadband` into `calculate_deterministic_metrics`?

1. kwarg. I think this is the way to go because it will be relatively easy to hook up to the user configuration from the dashboard report creation form.
2. lookup from `processed_fx_obs.original.observation`. If this, we'll need a way to control whether this should actually be used. 

Question 2: How do we actually implement the deadband?

1. Pass the `deadband` to the metrics functions that support it and implement within each function.
2. ~Add a `'mask'` column to `df` in `calculate_deterministic_metrics` and only pass the right data into the appropriate metrics functions.~ This doesn't work.
3. Create a new `obs_masked = np.where(error <= deadband * obs, fx, obs)` and pass that into the appropriate metrics functions. I guess do the same for `obs_masked_ref = np.where(error <= deadband * obs, ref_fx, obs)`

Question 3: What are the appropriate metrics functions and how do we define them?

1. All (deterministic) functions allowed
2. Define new `_DEADBAND_ALLOWED = ['mae', 'nmae',...]`

Probably missed some other stuff.

Thoughts @alorenzo175 @dplarson @awig?

**Comment by dplarson** [comment]
> Question 1: How do we get deadband into calculate_deterministic_metrics?

I agree with the `kwarg` approach.

> Question 2: How do we actually implement the deadband?

I would lean towards passing the `deadband` parameter to the metric functions.

> Question 3: What are the appropriate metrics functions and how do we define them?

While all the current deterministic functions should be able to support the deadband in theory, I think the idea of adding a `_DEADBAND_ALLOWED` is the right approach regardless of whether we revise all functions or only a subset for the deadband.
