### ISSUE TITLE
Add plotly to pdf functionality

### ISSUE THREAD

**Issue by lboeman** [SolarArbiter/solarforecastarbiter-core#360]
Following #359 we'd like to generate pdfs of metrics plots for report generation

Adding a pdf field to the `PlotlyReportFigure` datamodel class and an `output_pdf` would make this workflow simple.

One issue here to  to be tackled is determining the encoding of the plotly pdf. decoding the bytes with into utf-8 or ascii fails but succeeds with latin-1 but I'm not sure if that is correct. Some googling didn't yield any immediate results on this.

The decoding of the returned bytes is going to be necessary for transmitting and storing storing the pdfs as json at the API, even if we are going to need to encode again to the original format for rendering. If this proves to be a pain, we could re-instantiate plotly figures from the provided spec and generate pdfs on the fly during the greater report pdf generation process.

**Comment by alorenzo175** [comment]
Turns out, PDFs can be encoded with ascii 85 https://en.wikipedia.org/wiki/Ascii85.
