### ISSUE TITLE
fix normalized metrics in reports

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-core#370]
Some combination of the `reports` and `metrics` packages need to be modified support NMAE, NRMSE, and NMBE. The beta4 version of the dashboard allows users to request NMAE, NRMSE, and NMBE metrics, so this needs to be fixed in beta5 or those options need to be removed from the dashboard. They currently report the unnormed values * 100 (for conversion to %).

There are 3 problems:

1. Get the right normalization for each observation.
2. Pass the right normalization to the metrics functions for each observation.
3. Figure out what to do when these metrics don't make sense (e.g. for air temperature).

Get the right normalization
-------

These constants should be defined by the metadata of the observation. One option:

```python
def observation_normalization(observation):
    if observation.units == 'MW':
        return observation.site.modeling_parameters.ac_capacity
    elif observation.units == 'W/m^2':
        return 1000
    else:
        raise  # or maybe return 1?
```

Certainly other ways to accomplish the same kind of lookup (e.g. based on variable).

Pass the data to the metrics functions
---------

Once we have the ability to get the normalization constant for each `Observation`, we need to get it down to the functions in `deterministic.py`. It's not clear how to do this.

`metrics.calculator.calculate_metrics` takes a `normalizater` kwarg and propagates it down to `calculate_deterministic_metrics`, `_apply_deterministic_metric_func`, and eventually the metric function of interest.

https://github.com/SolarArbiter/solarforecastarbiter-core/blob/7c933afe97307a35057a9eeae1bc92e60d129d7b/solarforecastarbiter/metrics/calculator.py#L26-L27

The `reports.main.create_raw_report_from_data` function uses `calculator` like this, and I don't think that should change:

https://github.com/SolarArbiter/solarforecastarbiter-core/blob/7c933afe97307a35057a9eeae1bc92e60d129d7b/solarforecastarbiter/reports/main.py#L172-L177

My instinct is `calculate_deterministic_metrics` should look up the right normalization for the `processed_fx_obs` and `normalizer` should be removed from `calculate_metrics` and `calculate_deterministic_metrics`. (Similar implications for `ref_fx_obs` based on https://github.com/SolarArbiter/solarforecastarbiter_dashboard/issues/214.) 

`ProcessedForecastObservation` already has a `normalization_factor` attribute, so it would just be a matter of assigning it when creating the object

https://github.com/SolarArbiter/solarforecastarbiter-core/blob/7c933afe97307a35057a9eeae1bc92e60d129d7b/solarforecastarbiter/datamodel.py#L1159-L1162

`ForecastObservation` (and `ForecastAggregate`) also has a `normalization` attribute

https://github.com/SolarArbiter/solarforecastarbiter-core/blob/7c933afe97307a35057a9eeae1bc92e60d129d7b/solarforecastarbiter/datamodel.py#L923-L925

What to do for other variables
--------

I don't think we want to tackle normalization for air temperature or wind speed. We could avoid calculating these metrics for these variables or we could make the normed versions equal to the standard versions. The latter is probably easier.

Other Context
--------

#118 discussed the definition of MAPE and #269 discussed how normalization should be performed

#171 added NRMSE and MAPE and #268 added NMAE and NMBE

I think we might have discussed a normalization attribute for `MetricValue` during the report refactor.

**Comment by wholmgren** [comment]
@alorenzo175 we're going to need your design guidance on this one.

**Comment by alorenzo175** [comment]
I always thought that N* would support a variety of normalization constants, e.g. max or mean power on each day or nameplate capacity. That's why normalization is included for ``ForecastObservation`` and ``ProcessedForecastObservation``. The idea being that is defined per pair like a reference forecast would be.

**Comment by alorenzo175** [comment]
I guess it would be more clear when comparing reports to use constant values per variable

**Comment by wholmgren** [comment]
> I guess it would be more clear when comparing reports to use constant values per variable, in which case it should be removed from the datamodel objects and just looked up in calculate_metrics

If I understand correctly, this would be a problem if I want to compare NMAE at multiple power plants of different sizes. 

> I always thought that N* would support a variety of normalization constants, e.g. max or mean power on each day or nameplate capacity. That's why normalization is included for ForecastObservation and ProcessedForecastObservation. The idea being that is defined per pair like a reference forecast would be.

Makes sense. Thinking about data propagation:

1. `api.process_report_dict` would need additional information to set `ForecastObservation.normalization` and `ForecastAggregate.normalization`. Sounds messy. Maybe those objects could instead use  `__post_init__`  to set scalar defaults.
2. `preprocessing.process_forecast_observations` would need to know how to convert the `ForecastObservation.normalization` into a `ProcessedForecastObservations.normalization_factor`. Simple to copy a scalar. Anything else would require more work than I think we should put into that design pattern at this time.

**Comment by alorenzo175** [comment]
> If I understand correctly, this would be a problem if I want to compare NMAE at multiple power plants of different sizes.

What i meant by constant is more like your `object_normalization` function, so NMAE at multiple plants of different sizes would use the defined capacity for each plant.

> Makes sense. Thinking about data propagation:
> 
>     1. `api.process_report_dict` would need additional information to set `ForecastObservation.normalization` and `ForecastAggregate.normalization`. Sounds messy. Maybe those objects could instead use  `__post_init__`  to set scalar defaults.

I think it would be a good idea to set the default in datamodel to `None` then use ``__post_init__`` to set it to the proper value based on the variable if not set in `object_pairs` in report parameters.

>     2. `preprocessing.process_forecast_observations` would need to know how to convert the `ForecastObservation.normalization` into a `ProcessedForecastObservations.normalization_factor`. Simple to copy a scalar. Anything else would require more work than I think we should put into that design pattern at this time.

Yup fine with me to only support scalar values for now

**Comment by wholmgren** [comment]
Ok so I think we're on the same page conceptually. 

Quick implementation question: `api.process_report_dict` becomes:

```python
        for o in rep_params['object_pairs']:
            fx = self.get_forecast(o['forecast'])
            norm = o.get('normalization')
            if 'observation' in o:
                obs = self.get_observation(o['observation'])
                pair = datamodel.ForecastObservation(fx, obs, normalization=norm)
            elif 'aggregate' in o:
                agg = self.get_aggregate(o['aggregate'])
                pair = datamodel.ForecastAggregate(fx, agg, normalization=norm)
```

or do we try to use the `from_dict` method?

**Comment by wholmgren** [comment]
and standardize on `normalization` or `normalization_factor`? It's not clear to me why they have different names.

**Comment by alorenzo175** [comment]
yes to the first implementation. 

> and standardize on normalization or normalization_factor? It's not clear to me why they have different names.

sure. Different names because the idea was that normalization_factor might not be a simple scalar
