### ISSUE TITLE
make sure daily validation is applied to data retroactively

### ISSUE THREAD

**Issue by alorenzo175** [SolarArbiter/solarforecastarbiter-core#377]
Right now, daily validation only runs for the past day, so if data prior to that is uploaded, daily validation is not applied. Possibly worth adding an internal flag to indicate if daily validation has been applied. Then we can either scan for periods that need daily validation applied or if data is accessed without daily validation, a job is created to do the daily validation in the background

**Comment by wholmgren** [comment]
#375 will need something similar
