### ISSUE TITLE
metrics subpackage requirements

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-core#4]
This issue is a place to start sketching the requirements for the metrics subpackage. I suspect we'll make new issues once we have a better idea of what we need.

The metrics subpackage should:

* Account for mismatches in time between the measured data and the forecast data. ~Measured data may be at irregular intervals. Fill forward or backward or interpolation may be allowed up to some time limit.~ Measured data will be piecewise regular (each upload is guaranteed to have regular intervals, but there could be gaps between uploads). Interval labels need to be accounted for.
* Compute statistics for subsets of a forecast evaluation time series. For example, a user may want to know the average hourly MAE for each day or month of a many-months length forecast evaluation time series.
* Account for data quality flags. We should not presume the outputs of the data qualification toolkit.
* Account for missing forecast data according to several well defined rules
* Use numpy/scipy/pandas statistics as much as possible. But, we should also make sure we understand how they behave in the corner cases.

**Comment by awig** [comment]
@wholmgren 
Hey Will, I'm having some trouble figuring out if the timeseries data actually exists and how to envision it being passed to be evaluated by the metrics module.

In the [datamodel.py](https://github.com/SolarArbiter/solarforecastarbiter-core/blob/master/solarforecastarbiter/datamodel.py#L286) file I see the metadata associated with the site, observations and forecasts, but I don't see anywhere that specifies the format of the timeseries data as is noted in the [Data Formats](https://solarforecastarbiter.org/datamodel/#data-formats) - so that they would be objects with pd.Series attributes.  I was envisioning that the evaluator would be passed 3 primary arguments:

1. Observation or list of observations as given in Data Formats
2. Forecasts or list of forecasts as noted in Data Formats
3. Context dict (as I've designed in metrics/context.py)

Also, I would like your feedback if the metrics' context and results should be pure dicts or dataclasses (similar to what you have done with the metadata objects for the data models)?

FYI: I moved our working fork to my github repo: https://github.com/awig/solarforecastarbiter-core instead of the private one.

**Comment by wholmgren** [comment]
> I don't see anywhere that specifies the format of the timeseries data as is noted in the Data Formats - so that they would be objects with pd.Series attributes.

Right. The Data Formats doc is for uploading/downloading. For internal use, assume `pd.Series`. We've not defined a class that combines the metadata and data. @alorenzo175 do you think that would be worthwhile or just use tuples/dicts on ad hoc basis? 

Also relevant: #88 introduces a paired ForecastObservation object. 

> Also, I would like your feedback if the metrics' context and results should be pure dicts or dataclasses (similar to what you have done with the metadata objects for the data models)?

Not sure. I had been thinking a dict until we have a better idea of what we're doing. I sketched what that might look like in #88 but just an idea.

**Comment by alorenzo175** [comment]
We certainly could define something like a ``ObservationTimeseries``in ``datamodel.py``that includes the ``Observation``and a DataFrame (columns: value, quality_flag). This nicely encapsulates everything, but  might get messy if you need to define a new ``ObservationTimeseries`` after resampling.

**Comment by wholmgren** [comment]
> might get messy if you need to define a new ObservationTimeseries after resampling.

Maybe something like:

```python
def resample_observationtimeseries(input_ObservationTimeseries, output_observation):
    output_ObservationTimeseries = # smart code, raise ValueError if not allowed
    return output_ObservationTimeseries
```

**Comment by awig** [comment]
I like the idea of the encapsulation at least so we can't misuse which timestamps, values and quality flags correspond, but will defer to your better judgements.

For now though, with just the simples use case 1 obs and 1 forecast (to keep it simple) I will write the metrics evaluator (main entry point for the metrics module) as:

```
# in metrics.evaluator.py

def evaluate((obs_timestamps, obs_values, obs_quality_flags), (fx_timestamps, fx_values), context):
    # all obs, fx values are pd.Series, tuples to keep the number of args small and force consistency
   
   # preprocessing (this is oversimplified, but is just an idea)
   proc_obs_timestamps, proc_obs_values = metrics.preprocess(obs_timestamps, obs_values, obs_quality_flags), context)
   proc_fx_timestamps, proc_fx_values = metrics.preprocess(fx_timestamps, fx_values, context)
   results['series']['observations']['timestamps'] =  proc_obs_timestamps
   results['series']['observations']['timestamps'] =  proc_obs_values
   results['series']['forecasts']['timestamps'] =  proc_obs_timestamps
   results['series']['forecasts']['timestamps'] =  proc_obs_values


   # calculate metrics
   for key,value in context.metrics.iteritems():
      if value:
           metric_func = func_map(key)  # map of keys to metric functions
           result['metrics'][key] = metric_func(proc_obs_values, proc_fx_values)
           # add groupings etc.

   return results
```

**Comment by wholmgren** [comment]
@awig I suggest not breaking things down quite that far. See link below for what the API will return for observations (DataFrame with DatetimeIndex) and forecasts (Series with DatetimeIndex):

https://github.com/SolarArbiter/solarforecastarbiter-core/blob/c9b747e263b756933f2707894662b16e6f703735/solarforecastarbiter/io/utils.py#L96-L135

**Comment by awig** [comment]
Aw okay. Great. that's what i needed.

**Comment by wholmgren** [comment]
I don't see anything discussed in this issue that hasn't already been addressed. There are a few more things we need to do (like add support for filling missing values with 0s) but they can be addressed in their own issues.
