### ISSUE TITLE
plotly timeseries plot does not use steps

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-core#415]
I can't remember if we discussed this or not (I can't find anything), but it appears the plotly time series plots do not use steps for interval averages. 

It seems that we need a function like `line_or_step` for the plotly graphs.

https://github.com/SolarArbiter/solarforecastarbiter-core/blob/d1254d15bc0d4f4405bbab2ad9f195cbbca77332/solarforecastarbiter/plotting/utils.py#L45-L77

It [appears](https://plotly.com/python/line-charts/) plotly's `line_shape` kwarg is the way to go. 

Am I missing something @alorenzo175?

**Comment by alorenzo175** [comment]
Look's like that's all that's needed to me. We might also want to use "markers+line" mode

**Comment by wholmgren** [comment]
I think the markers make the plot too busy and the hover tool should make it clear enough.

![newplot(3)](https://user-images.githubusercontent.com/4383303/80254171-8b7c8580-862f-11ea-82e6-d3b74ad73ac9.png)
![newplot(4)](https://user-images.githubusercontent.com/4383303/80254174-8d464900-862f-11ea-9630-d0c02394ec55.png)
![newplot(5)](https://user-images.githubusercontent.com/4383303/80254178-8f100c80-862f-11ea-8af1-42062613e4e7.png)
![newplot(6)](https://user-images.githubusercontent.com/4383303/80254181-90d9d000-862f-11ea-9543-462e05354953.png)
