### ISSUE TITLE
improve metrics table formatting for many metrics

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-core#418]
lots of overlapping stuff in this screenshot

<img width="892" alt="Screen Shot 2020-04-24 at 4 20 08 PM" src="https://user-images.githubusercontent.com/4383303/80264027-80355400-8647-11ea-960f-a85376a17cb5.png">

maybe just a smaller font

**Comment by awig** [comment]
Can you assign to me please?

**Comment by lboeman** [comment]
@awig Have you made progress on this issue? If not, I can work on it. It seems like this affects many of the report tables.
