### ISSUE TITLE
make plotly scatter plot have a 1:1 aspect ratio

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-core#419]
Want the plot to use the same amount of x and y space.

![newplot(10)](https://user-images.githubusercontent.com/4383303/80264085-b8d52d80-8647-11ea-9b6b-060da47578a3.png)

Probably tricky to do while remaining responsive. We hacked around it for bokeh but it was fragile.

**Comment by alorenzo175** [comment]
![image](https://user-images.githubusercontent.com/4625457/92970221-2933ee00-f433-11ea-8d96-211c4aab2f02.png)

**Comment by alorenzo175** [comment]
at least the grid lines are 1:1

**Comment by wholmgren** [comment]
I think the issue is related to legend width. What do you mean 1:1 for the most part? Grids are 47x47 pixels on my screen.

**Comment by alorenzo175** [comment]
> I think the issue is related to legend width. What do you mean 1:1 for the most part? Grids are 47x47 pixels on my screen.

Just the first column from -1?? to 200, so not so important
