### ISSUE TITLE
Add reference net load observations

### ISSUE THREAD

**Issue by dplarson** [SolarArbiter/solarforecastarbiter-core#431]
We should add reference net load observations so that we can more fully demonstrate reference net load forecasting.

For ISO/RTO/utility level data, we can leverage the EIA Open Data API (https://www.eia.gov/opendata/), which provides hourly-resolution net load data for all areas across the US. Additionally, some (but not all) areas listed in the EIA API have solar generation data. Note: the EIA Open Data pulls directly from public sources and does not include any discernible quality control/validation of the data.

I would suggest starting with the ISOs/RTOs, but once we get one area set up, it should be trivial to add other areas (since the data is standardized via the API).

**Comment by dplarson** [comment]
Following up on this: I would suggest we start with the main ISOs/RTOs: CAISO, ERCOT, ISO-NE, NYISO, MISO, PJM and Southwest Power Pool (SPP).

Would a good first step be a PR that adds `solarforecastarbiter/io/fetch/eia.py` and `solarforecastarbiter/io/reference_observations/eia.py` (similar to the PVDAQ and RTC code)?

**Comment by wholmgren** [comment]
Yes, that sounds great. Note that @lboeman recently added a detailed description of the reference observations patterns: https://solarforecastarbiter-core.readthedocs.io/en/latest/reference-observations.html
