### ISSUE TITLE
missing GEFS constant values for reference site

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-core#450]
/Sites/NOAA SURFRAD Bondville IL/Probabilistic Forecasts/Bondville IL Day Ahead GEFS ghi

https://dashboard.solarforecastarbiter.org/forecasts/cdf/d73dc8b8-0809-11ea-990e-0a580a8003a5

Maybe others?

**Comment by alorenzo175** [comment]
Only Bondvill GHI and DNI were missing. Should be fixed now
