### ISSUE TITLE
add limits tests for DC and AC power

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-core#452]
This could be coarse like values > 0 + epsilon at night and values greater than 1.x times DC or AC capacity during the day. A separate function could be implemented for clear sky exceeded flags that's more careful (tracked in #200).

@cwhanse @wfvining I took a quick look at pvanalytics and didn't see any functions that addressed this. Did I miss something? Do you have any recommendations here?

For reference, #15 and #29 addressed limits checks for irradiance, temperature, and wind.

**Comment by cwhanse** [comment]
We haven't gotten to limit testing in pvanalytics. 

Note that AC power can be negative at night if measured at the inverter, since inverters use a small amount of power to monitor the DC input and grid connection to decide if it should turn on.

**Comment by wfvining** [comment]
Is a generic function that takes a boolean series (e.g. day/night mask), a data series, and two sets of limits where one limit applies for values flagged `True` and the other for `False` something that could be useful in general?

**Comment by wholmgren** [comment]
@wfvining maybe, but I decided to only support a single low limit for both night and day in #458.
