### ISSUE TITLE
immediate and daily validation functions for more variables

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-core#453]
We currently have immediate validation tasks:

https://github.com/SolarArbiter/solarforecastarbiter-core/blob/8ef997ee71a44c65c68dc5f58ae44feab39eb333/solarforecastarbiter/validation/tasks.py#L346-L354

and daily validation tasks:

https://github.com/SolarArbiter/solarforecastarbiter-core/blob/8ef997ee71a44c65c68dc5f58ae44feab39eb333/solarforecastarbiter/validation/tasks.py#L383-L387

I think we should add daily tasks for all variables at this point. The only difference for most (all?) is the addition of stale and interpolated checks for daily data.

**Comment by wholmgren** [comment]
We also need immediate validation for power.

**Comment by alorenzo175** [comment]
I don't think we need an entry for each variable. The functions that apply validation already take into account if there is a missing function for the variable and just applies the defaults. #482 adds the default for daily validation
