### ISSUE TITLE
Avoid stacking in total metric plots

### ISSUE THREAD

**Issue by alorenzo175** [SolarArbiter/solarforecastarbiter-core#463]
Seems like abbreviation causes some metrics to get stacked. We should also alter the hover name to be the full name instead of abbreviated for easier distinction.

![image](https://user-images.githubusercontent.com/4625457/83045432-69916c80-9ffa-11ea-8c6f-0f4f80d6b395.png)

**Comment by wholmgren** [comment]
Yuck. I think we should fix sooner (rc) than later.
