### ISSUE TITLE
add probabilistic forecast container to data model

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-core#47]
Should be comprised of a set of standard forecast containers

**Comment by wholmgren** [comment]
@alorenzo175 @lboeman I thought you said on Monday that the probabilistic forecast data model had been implemented across the stack, but I don't see it in `datamodel.py`. Looks like we'll also need to add functions to `api.py`.

**Comment by lboeman** [comment]
At the moment, Probabilistic forecasts have only been implemented in the API and Dashboard but not yet in core. I'll add an issue for the `api.py` addition.
