### ISSUE TITLE
text wrap in report metadata table

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-core#475]
Broken words are bad:

<img width="857" alt="Screen Shot 2020-06-03 at 8 42 13 AM" src="https://user-images.githubusercontent.com/4383303/83657810-34df6100-a576-11ea-8aaa-8f6382a915a2.png">

**Comment by wholmgren** [comment]
@lboeman can you take a quick look at this?

**Comment by lboeman** [comment]
So the wrap for this table is set to `break-word` which was a fix for issues like this: 
![Screenshot from 2020-09-14 14-34-53](https://user-images.githubusercontent.com/21206164/93140557-829c5700-f697-11ea-8a22-a370b3cb2de9.png)

One thing we can do to ensure that at least, arbiter provided language such as interval labels and such don't wrap is to reduce the padding on these tables. The result of a reduction from .75rem to .5rem is below:
![Screenshot from 2020-09-14 14-36-56](https://user-images.githubusercontent.com/21206164/93141084-68af4400-f698-11ea-8711-92fd6a440381.png)

**Comment by wholmgren** [comment]
looks good to me, thanks!
