### ISSUE TITLE
Process report dict forecast_type handling

### ISSUE THREAD

**Issue by lboeman** [SolarArbiter/solarforecastarbiter-core#486]
https://github.com/SolarArbiter/solarforecastarbiter-core/blob/8cee38271464d11954c53e8ab2606e873d01da75/solarforecastarbiter/io/api.py#L833
uses the `forecast_type` of an object pair to search for an attribute function in the pattern `get_<forecast_type>`. Event forecasts are causing an `AttributeError` because there is no `get_event_forecast` method in APISession. Event forecasts should be able to use the `get_forecast` method, so the fix may just be a check for this case and manually set the `fx_method`.

**Comment by wholmgren** [comment]
Let's make the method mapping explicit instead of relying on getattr and special-casing events.
