### ISSUE TITLE
Fix metrics, preprocessing, validation tables when one field is not available

### ISSUE THREAD

**Issue by alorenzo175** [SolarArbiter/solarforecastarbiter-core#504]
![image](https://user-images.githubusercontent.com/4625457/86187049-b8e22580-baef-11ea-91c4-d3f0b9e56d9e.png)

First val should be over in CRPS column

**Comment by wholmgren** [comment]
same issue for data validation table?

<img width="875" alt="Screen Shot 2020-07-02 at 1 06 54 PM" src="https://user-images.githubusercontent.com/4383303/86404701-edc3b900-bc64-11ea-8c3d-320fe9f24a1d.png">
