### ISSUE TITLE
add report's reference forecasts to plots, metrics tables

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-core#511]
The current behavior of the report generation process is to exclude reference forecasts from the time series or metrics tables (unless they've been manually selected as additional objects). The skill score is a lot easier to reason about if you have the metrics for the reference forecast. So I wonder if instead we should insert them into these results. This could be done in core or we could consider this to just be a dashboard feature.

**Comment by wholmgren** [comment]
This just tripped me again. 

Another alternative might be to add a warning to the dashboard form if it's not included.

What do you think about this @alorenzo175 @lboeman?

**Comment by alorenzo175** [comment]
I would rather do it on the dashboard. I think a warning is a good idea

**Comment by lboeman** [comment]
Do you think this should be a  a warning that reacts to the users input? e.g. display a warning  if a reference forecast is selected, but not added as a separate obs-fx pair? Or just some static text?

**Comment by wholmgren** [comment]
I was thinking of something like the conditional warning you described but it sounds tedious to manage. 

Good static text would be easier and might be more clear but I'm not sure how to make it work without being distracting. 

"Select a reference forecast (Optional)" could become "Select a reference forecast for skill metric (Optional)" implying that other metrics might not be calculated. Doesn't feel good enough though. Maybe "Select a reference forecast (Optional. Skill only.)". Still not great.

Not sure if this would work with formatting constraints around the selection and filter boxes, but here's another idea: 

**Select a reference forecast for skill metric (Optional. Skill only.)**
Create a new pair with this forecast to compute all selected metrics.

**Comment by wholmgren** [comment]
Or maybe a check box or additional button to add a new pair for the reference forecast.

**Comment by lboeman** [comment]
> Or maybe a check box or additional button to add a new pair for the reference forecast.

I like that idea. I think a checkbox paired with the **Select a reference forecast for skill metric (Optional. Skill only.)** message might be the most straight forward solution for the end user.

**Comment by wholmgren** [comment]
I forgot that it's not just about the metrics, it's also about the presence/absence of the reference forecast on the time series and scatter plots. So that's another communication challenge. Here's another imperfect idea:

Select a reference forecast (Optional). `[radio, default]` Also include as standard forecast. `[radio]` Use only for skill metric.

**Comment by wholmgren** [comment]
closed by https://github.com/SolarArbiter/solarforecastarbiter-dashboard/pull/349
