### ISSUE TITLE
inconsistent SRML PV reference forecast names

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-core#521]
These names are hard to understand, particularly for the persistence forecasts

https://dashboard.solarforecastarbiter.org/forecasts/single/?site_id=96662e54-7e49-11e9-ba57-0a580a8003e9

Some names use "30 deg tilt", some use "30 deg til", and some use "30 deg".

The 15 degree site also has some weird forecasts:

https://dashboard.solarforecastarbiter.org/forecasts/single/?site_id=c2e91bfa-a4fd-11ea-b630-0a580a80039b

"15 deg", "15 de", "15 deg t", "15 deg til", "15"

The Kalapuya site:

https://dashboard.solarforecastarbiter.org/forecasts/single/?site_id=94cb53ba-7e49-11e9-acfe-0a580a8003e9

"OR", "O", "OR P", "OR PV"

I didn't notice any issues at the other SRML PV sites but would be worth double checking.

**Comment by alorenzo175** [comment]
The names are truncated to fit in the 64 character limit. It would probably be better to cut entire words after shortening known patterns (e.g. Persistence -> Pers. or similar)

**Comment by wholmgren** [comment]
That makes sense. Could drop the variable from the name too. Is there a reason we spell out fifteen-minute and five-minute?
