### ISSUE TITLE
persistence forecasts

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-core#53]
The `reference_forecasts` subpackage needs to be able to make persistence forecasts.

Persistence flavors include:

1. Persistence of measured value
2. Persistence accounting for solar position using a clear sky model
3. Persistence of clearness index (stakeholder request at AMS)

Input data... I'm assuming that persistence will use data that has been processed by the validation toolkit. It will have a well-defined frequency. Missing data may be labeled with NaN or may not exist. 

It's straightforward to take the last value and make a persistence forecast from that. One could debate the rules and flexibility around the *interval length* of the observation and the *interval length* of the desired forecast. I suggest that we provide no flexibility and require that persistence forecasts of a given *interval length* be derived by observations resampled to the same *interval length*. I don't think the *lead time to start* should matter for any lead time (including day ahead persistence). 

| Obs interval length | Fx interval length | Fx lead time | Fx run length | Obs slice | resampler |
|--------------------|------------------|--------------|--------------|-----------|-----------|
|5 min | 5 min | Any | 5 min | [-1:] | None |
|5 min | 60 min | Any | 60 min | [-12:] | mean |
|5 min | 5 min | Any | 60 min | [-12:] | None |
|60 min | 5 min | Any | Any | [-1:]? Exception? | ? |
|60 min | 60 min | Any | 60 min | [-1:] | None |

Data flow... in #52 we established a data flow like this:
```
# model is a function defined in models.py
main.run(site, model, init_time, start, end,...)
    model(lat, lon, init_time, start, end,...)
        io.nwp.load_data(lat, lon, init_time, start, end...)
```
A similar data flow for this might look like
```
# model is a function defined in models_persistence.py
main.run_persistence(site, model, init_time, start, end,...)
    model(site, init_time, start, end,...)
        io.database.load_data(site, init_time, start, end...)
```
The point is that the call to `io.database.load_data` is buried within some other function that only knows about the metadata. I'm not committed to parallelism with the NWP data flow. An alternative might look like:
```
main.run_persistence(site, init_time, start, end,...)
    data = io.database.load_data(site, init_time, start, end...)
    return persistence(site, init_time, start, end,...)

main.run_clearsky_persistence(site, init_time, start, end,...)
    data = io.database.load_data(site, init_time, start, end...)
    csi = clearsky() / data
    csi = persistence(csi)
    return clearsky_index_to_irrad_or_power(csi)
```

For reference, @cwhanse implemented persistence and ARMA forecasts in https://github.com/pvlib/pvlib-python/pull/543/files but I think we can avoid some of the complications of that code if we make the assumptions discussed above.

**Comment by cwhanse** [comment]
I don't see the difference between flavor 2 and 3.  Persistence for irradiance forecasts should account for sun position. Persistence for AC power should first calculating the time window that the system would clip under clear sky conditions: within the window, use flavor 1; outside the window, use flavor 2 / 3 by calculating an AC power index.

> It's straightforward to take the last value and make a persistence forecast from that. 

Rather than last value, I would forecast a statistic of the recent data (e.g., mean, median), which requires an additional parameter defining the data window for calculating the statistic.  I would avoid making any persistence forecast for instantaneous interval type.

**Comment by wholmgren** [comment]
Let's set aside 3 (persistence based on clearness index) for now. We discussed a few months ago and nobody thought it was a high priority.

> Persistence for irradiance forecasts should account for sun position.

Are you against providing an option to use flavor 1 (measurement persistence) for both irradiance and power? I think the default behavior should be that persistence accounts for sun position for both irradiance and power, but I suspect that we will get push back if we insist that persistence forecasts *always* account for sun position.

> Persistence for AC power should first calculating the time window that the system would clip under clear sky conditions: within the window, use flavor 1; outside the window, use flavor 2 / 3 by calculating an AC power index.

I suggest kicking the switching complication down the road. I think we'd get push back against the complexity of that approach for some applications. Can you point me to any comparisons of using the switching approach over using AC power index at all times? 

> Rather than last value, I would forecast a statistic of the recent data (e.g., mean, median), which requires an additional parameter defining the data window for calculating the statistic. 

I attempted to get at what that would look like for a handful of cases in the table above. Is the table consistent with your recommendations? GitHub makes it difficult to quote and edit tables, so the raw table code is provided at the end if you'd like to edit it.

> I would avoid making any persistence forecast for instantaneous interval type.

I think it's ok if the observation interval type is also instantaneous (some of the reference data is like this) and no windowed averaging is performed, but I'm also ok saying not allowed for now.

@alorenzo175 comments on any of this, especially data flow?

```
Table of suggested persistence behavior

| Obs interval length | Fx interval length | Fx lead time | Fx run length | Obs slice | resampler |
|--------------------|------------------|--------------|--------------|-----------|-----------|
|5 min | 5 min | Any | 5 min | [-1:] | None |
|5 min | 60 min | Any | 60 min | [-12:] | mean |
|5 min | 5 min | Any | 60 min | [-12:] | None |
|60 min | 5 min | Any | Any | [-1:]? Exception? | ? |
|60 min | 60 min | Any | 60 min | [-1:] | None |
```

**Comment by cwhanse** [comment]
Is the difference between 2 and 3 the use of clearsky vs. clearness index?  If so, then I agree - defer 3 for now.

I'm not against offering both value persistence and clear-sky persistence.

> I think the default behavior should be that persistence accounts for sun position 
Agree.

> Can you point me to any comparisons of using the switching approach over using AC power index at all times?

No.  The switching approach is my attempt to improve upon the AC index persistence, which will not work well for systems that clip, even during clear-sky conditions. Here's a cartoon comparing the two approaches (by value and by index):

![image](https://user-images.githubusercontent.com/5393711/55506619-1fd60d80-5613-11e9-831f-3bddf1a69992.png)

You can see that switching from index to value and back gives a forecast that better follows the clipped shape that either method alone.

>  Is the table consistent with your recommendations?
2nd row is: |5 min | 60 min | Any | 60 min | [-12:] | mean |
3rd row is not: |5 min | 5 min | Any | 60 min | [-12:] | None |

In the case of the third row, how are the 12 observation values used to produce the 12 forecast values? Here, I think the observations should be reduced to a statistic that is projected forward.

> I think it's ok if the observation interval type is also instantaneous
The issue is projecting an instantaneous value using from observation data that are changing.  Imagine a rapid, large ramp event.  The forecast depends strongly on how the data sampling aligns, or not, with the ramp.

**Comment by wholmgren** [comment]
> Is the difference between 2 and 3 the use of clearsky vs. clearness index? If so, then I agree - defer 3 for now.

Yes. Deferred.

> You can see that switching from index to value and back gives a forecast that better follows the clipped shape that either method alone.

Hm, what exactly is your model? I was thinking:

AC(t0 + delta_t) = ( AC(t0) / AC_clear(t0) ) * AC_clear(t0 + deltat) 

where AC(t0) is observed power at t0, AC_clear(t0) is the modeled power at t0 using modeled clear sky irradiance as the input, similarly for AC_clear(t). Now that I think about it, I expect you're calculating this:

AC(t0 + delta_t) = ( AC(t0) / GHI_clear(t0) ) * GHI_clear(t0 + deltat) 

Or similarly for POA. The GHI version has the advantage that it does not need any system metadata or power modeling.

> 3rd row is not: |5 min | 5 min | Any | 60 min | [-12:] | None |
> In the case of the third row, how are the 12 observation values used to produce the 12 forecast values? Here, I think the observations should be reduced to a statistic that is projected forward.

My intention was simply `fx = obs[-12:]`. It sounds like you'd like `fx = np.full(12, obs[-12:].mean())`. (with appropriate reindexing for both.) Both of these formulations have issues. The first fails to account for newer data. The second will produce a forecast with 0 variance during each hour. That makes some metrics harder to interpret, but that's not the end of the world. Your formulation is probably easier to explain.

**Comment by cwhanse** [comment]
> Hm, what exactly is your model? I was thinking:
AC(t0 + delta_t) = ( AC(t0) / AC_clear(t0) ) * AC_clear(t0 + deltat)
where AC(t0) is observed power at t0, AC_clear(t0) is the modeled power at t0 using modeled clear sky irradiance as the input, similarly for AC_clear(t). Now that I think about it, I expect you're calculating this:
AC(t0 + delta_t) = ( AC(t0) / GHI_clear(t0) ) * GHI_clear(t0 + deltat)

The GHI version.  Good point.  I'm working from a recent project where we couldn't assume we knew system specs with any confidence and only had AC power and clear-sky GHI to work from.  If system specs are known, then the AC_clear method is effective.

> My intention was simply fx = obs[-12:]. It sounds like you'd like fx = np.full(12, obs[-12:].mean()). 

`fx = obs[-12:]` will push forward the same shape as observed in the past, e.g., if a shadow passed over between -10 and -8, then that shadow will repeat in the forecast between 2 and 4.  You are correct that pushing a statistic will not represent the variability in the recent data.  I suppose much depends on the intent of the forecast. In the recent project that is coloring my opinion, the forecast was interpreted as the best time-averaged value for each interval.

**Comment by alorenzo175** [comment]
separate run functions might be easier now, but I think having the separate models will be easier to extend in the future. Also, keeping the data loading in the model function makes it clear what the requirements of the model are.
