### ISSUE TITLE
some PVDAQ sites are missing

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-core#539]
The `#` sign in these names causes pandas to treat the rest of the row as a comment, so all of the remaining metadata is set to `NaN`. 

https://github.com/SolarArbiter/solarforecastarbiter-core/blob/5dfed355bee24f2192e169d0a596f2b5e3f97823/solarforecastarbiter/io/reference_observations/sfa_reference_sites.csv#L224-L225

```python
site_file = reference_data.DEFAULT_SITEFILE
all_sites = pd.read_csv(site_file, comment='#')
network_filtered_sites = all_sites[all_sites['network'].isin(network)]
```

<img width="1141" alt="Screen Shot 2020-07-31 at 3 48 09 PM" src="https://user-images.githubusercontent.com/4383303/89083256-490cc800-d345-11ea-9dec-85401d84ccfb.png">

Looks like this applies to 8 systems. Easiest thing seems to be to delete the `#` and in one case replace it with a space. @alorenzo175 any API/database things to be aware of while fixing this?

**Comment by alorenzo175** [comment]
I don't think so. The sites didn't get created so should be fine, otherwise I would say we should delete the old ones asap.
