### ISSUE TITLE
probabilistic reference forecasts from NWP

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-core#54]
Some options include:

* statistics using historical data
* Global Ensemble Forecast System cloud cover. 0.5 deg, 21 members, 7+ days. [GEFS](https://nomads.ncep.noaa.gov/txt_descriptions/GFS_Ensemble_high_resolution_doc.shtml)
* HRRR Ensemble irradiance or cloud cover. Not operational. Perhaps available from ESRL ftp.
* High Resolution Ensemble Forecast System. 3 km, 8 members, 36 hrs. [HREF](https://nomads.ncep.noaa.gov/txt_descriptions/HREF_doc.shtml). [AMS 2018](https://ams.confex.com/ams/98Annual/webprogram/Paper334406.html)
* Short Range Ensemble Forecast System. 16 km, 21 members, 3 days. [SREF](https://nomads.ncep.noaa.gov/txt_descriptions/SREF_doc.shtml)?

I won't start implementing this until #10 and #53 are complete.

**Comment by wholmgren** [comment]
I suggest that we only implement GEFS-based forecasts for alpha and decide if we want/need anything else after that.

**Comment by wholmgren** [comment]
Working on GEFS forecasts now. If we have a function like `reference_forecasts.models.gefs_half_deg_to_hourly_mean`, what exactly should it return? The other functions in this module return a tuple of:

  * ghi : pd.Series
  * dni : pd.Series
  * dhi : pd.Series
  * air_temperature : pd.Series
  * wind_speed : pd.Series
  * resampler : function
  * solar_position_calculator : function

Should the new function return a tuple of 21 tuples of the above (21 = 1 control + 20 permutations)? Or something like `((ghi, dni, dhi, wind, temp), ...), resampler, solposcalc`? Is there any reason we'd want to expose the ability to load individual members (I think no)?

The `reference_forecasts.main.run_nwp` function will need to be modified (or a new `run_probabilistic_nwp` function will need to be written) to compute the probabilities based on the output (optionally processed through power) from the proposed `gefs_half_deg_to_hourly_mean` function.

@alorenzo175 any initial thoughts or should I hack away?

**Comment by wholmgren** [comment]
Probably want to add a `solar_position=None` kwarg to `_resample_using_cloud_cover` to avoid repeated computation. In the case of 21 tuples of the full output, `solar_position_calculator()` would point to the same object. Guess we could invoke `copy()` on the DataFrame if we didn't want that for some reason.

**Comment by alorenzo175** [comment]
I think having a separate ``run_probabilistic_nwp`` is probably better. I like avoiding returning things multiple times (resampler, solposcalc). Maybe best for consistency is ``(ghi0, ..., ghi21), (dni0...), ..., resampler, solposcalc``. Maybe this is a case where a dataframe per variable makes sense assuming the same processing is done on each column before probability calc

**Comment by wholmgren** [comment]
Ok, thanks. I agree that your return signature seems a little more consistent with the API. For processing wx data into power, maybe `(ghi0, dni0,...)...(ghi21, dni21...), resampler, solposcalc` is still preferable because it preserves correlation among the variables in each ensemble member. Maybe we just need a couple of functions to go between the tuple representations no matter which way we go.
