### ISSUE TITLE
Add NASA Langley CAPABLE BSRN site

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-core#541]
Larry Berg and Matt Wiley use this site.

https://capable.larc.nasa.gov/data/

https://cove.larc.nasa.gov/BSRN/LRC49/

Data from December 2014 to present. 

1 month of data per file. Appears to be uploaded in the first few days of the following month. 1 minute intervals.

Another fun fixed width file. Entries like:

```
  1  987   1003 -99.9 -999 -999    975 -99.9 -999 -999
             72 -99.9 -999 -999    287 -99.9 -999 -999     19.9  37.2 1026
  1  988   1006 -99.9 -999 -999    977 -99.9 -999 -999
             72 -99.9 -999 -999    290 -99.9 -999 -999     19.8  36.9 1026
```

```
  1 1438     22 -99.9 -999 -999      0 -99.9 -999 -999
             21 -99.9 -999 -999    307 -99.9 -999 -999     17.7  57.9 1023
  1 1439     21 -99.9 -999 -999      0 -99.9 -999 -999
             20 -99.9 -999 -999    307 -99.9 -999 -999     17.6  56.8 1023
```

The first number is the day of the month. The second is the minute of the day. Times appear to be in UTC.

I believe the ordering is:
* CM22 pyranometer GHI (upper left)
* CM31 pyranometer DHI (lower left)
* CH1 pyrheliometer DNI (upper right)
* PIR infrared (lower right)

I'd need to write the parser and plot it to be sure.

CAPABLE Site Coordinates:
Latitude:  37.1038
Longitude:  -76.3872
Elevation: 3 m ASL

**Comment by alorenzo175** [comment]
with #604, now just waiting on data parsing procedures before implementing ``fetch``
