### ISSUE TITLE
Marker opacity in report scatter plot

### ISSUE THREAD

**Issue by williamhobbs** [SolarArbiter/solarforecastarbiter-core#547]
In the report scatter plots of forecast vs observed values, using marker opacity to make markers partially transparent might make it easier to see density/trends in large datasets. For example, in the chart below, it is hard to tell if the points where GFS values are ~1/3 of observations are outliers compared to the 1:1 "cluster".

![newplot](https://user-images.githubusercontent.com/45701090/91316496-7b5fe880-e77e-11ea-8bbd-14883f47b2d5.png)

**Comment by wholmgren** [comment]
Thanks @williamhobbs that's a good idea! Do you want to make a pull request?

**Comment by williamhobbs** [comment]
Thanks. I'll admit I've never done a pull request. If I find time to figure it out, I may give it a try, but don't hold your breath...
