### ISSUE TITLE
net load reference forecasts

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-core#55]
From our [AMS 2019 poster](https://solarforecastarbiter.org/assets/posters/AMS%202019%20Benchmark%20Solar%20Power%20Forecasts.pdf):

The Solar Forecast Arbiter will support net load benchmarks that account for behind the meter (BTM) PV and metered PV, but not other renewables.

✅ net load = true demand - BTM PV - metered PV
✅ net load = true demand - BTM PV
❌ net load = true demand - all renewables

The benchmark forecast may comprise a regression of load on weather variables.

**Comment by wholmgren** [comment]
What would this look like in practice? One possibility:

1. User defines Site or Aggregate corresponding to net load. We'd need to define a variable type for net load.
2. User defines Sites or Aggregates corresponding to the BTM PV and metered PV in net load.
2. User uploads net load data. This the standard known load data for most utilities for the case "net load = true demand - BTM PV". We could require utilities to subtract off their own metered PV if they want to include that in the definition, but I think we already committed to computing positive sums for aggregates, so probably reasonable to do that adjustment here, too.
2. For the times in the data upload, Arbiter computes BTM PV based on NWP forecast data and BTM PV metadata. This, possibly combined with uploaded metered PV data, gives the Arbiter an estimate of true demand.
2. Arbiter users predefined time range to compute regression of true demand on NWP forecast a) temperature (minimum), b) temperature and dew point temperature (recommended), c) temperature, dew point temperature, wind speed, irradiance (too much, I think)? Maybe 3rd order polynomial for temperature, 1st order for dew point temperature and any others. I'm going to guess that 1-3 months of data leading up to the forecast period is sufficient for our purposes. It's also better to avoid sliding windows if possible. 
2. Arbiter uses regression results to compute true demand forecasts, and BTM/metered PV metadata to compute net load forecasts.

I think it's doable so long as the metadata is good, the input data is good, and we have a high tolerance for bad forecasts. We could simplify things somewhat by requiring that net load reference forecasts be hourly interval average. We could also use only GFS for net load reference forecasts.

In the long run, this requires aggregates in the datamodel (#61) but maybe we can make it work with sites for now.

**Comment by dplarson** [comment]
Following up from today's team call:

A reasonable initial model would be a Smart Persistence forecast, which uses a dynamically estimated "clear-sky" load model that is a function of 1) the hour of the day and 2) weekday vs weekend. It won't be state-of-the-art, but it would provide a decent lower bound on performance, is fairly straightforward to implement using pandas, and only requires the load time-series as input.

**Comment by dplarson** [comment]
@wholmgrem As part of adding this feature, would it be okay to commit a small (<5 MB) CSV file of load data (to then be used by the tests)? Or do we want to avoid committing data files to the repo and (if necessary) pull data from external sources for, e.g., tests?

**Comment by wholmgren** [comment]
no objection to that size of csv file if it makes the tests better/easier. We already have files of this size for testing io stuff.
