### ISSUE TITLE
accounting for marginal nighttime and clearsky conditions when resampling observations

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-core#556]
Let's say we want to compare 1 minute observations of GHI to hourly forecasts of GHI, but exclude nighttime data. We define nighttime as solar zenith > 87 degrees at the time label (regardless of interval length - a separate issue).

We discard any "nighttime" values from the observations series, resample the results to hourly average, and compute the metrics. If 90% or more of 1 minute values are nighttime then we set the interval to NaN, and it will be dropped from the comparison.

The problem is that our procedure requires that forecasters use the same definition of nighttime. Even for a perfect forecast, a forecaster than defines nighttime as solar zenith > 90 degrees will compute and submit a slightly different hourly average than we'll calculate from observations.

I don't see a way out of this other than to exclude any interval that contains a single nighttime point.

**Comment by wholmgren** [comment]
Thinking about this a little more, the same issue occurs for resampling any flag associated with "good" data. For example, say we want to exclude clear sky conditions from the analysis. Within an hour, there may be some clear minutes and some cloudy minutes. If you throw out the clear minutes and then resample, you're left with an inaccurate hourly average. 

For "bad" data, we really do just want to throw it out and do our best with the remaining data within the interval, so no problem with those flags.

**Comment by wholmgren** [comment]
I had concluded that we could simply discard any hour for which there are any clear sky points, similar to what I'm proposing for nighttime. But that means we would exclude any periods with broken cloud fields and thus high variability. These conditions are important and challenging, so that won't work. 

Here's a recent example from the UA MIDC site. A handful of short clear sky periods would cause much of this day to be discarded if using a rule of "discard if any clearsky in a one hour interval".

<img width="872" alt="Screen Shot 2020-09-10 at 10 53 52 AM" src="https://user-images.githubusercontent.com/4383303/92776289-fb2bac80-f353-11ea-93ed-39d92b7978fa.png">

Another example. Here I'd definitely throw out an hour or two in the afternoon. The early to mid-morning is debatable. I'd want to keep all of the mid-morning to early afternoon hours.

<img width="868" alt="Screen Shot 2020-09-10 at 11 12 46 AM" src="https://user-images.githubusercontent.com/4383303/92779402-e13f9900-f356-11ea-8f9c-d34efcc9dc6c.png">

One more example. Here I'd argue we should discard the early to mid morning hours with the tiny blips, especially for the one around 16:30 UTC. I'd probably keep the entire afternoon.

<img width="858" alt="Screen Shot 2020-09-10 at 11 16 36 AM" src="https://user-images.githubusercontent.com/4383303/92779962-5c08b400-f357-11ea-92d4-67bf600f99c7.png">


Perhaps we need a rule like

```
if fraction clear sky points in interval > ~90%:
    interval = nan
else:
    interval = average of all points in interval (including clear sky points)
```

The same logic could be used for the nighttime issue - the important thing is that the average now includes all points in the interval.

I'm not entirely sure about the threshold value. My third example suggests that a single minute or two should not meet the threshold. 12 minutes (80%) feels too low. So, 6 minutes (90%) feels ok to me. Perhaps it should be more closely related to how the algorithm works.

In any case, the pseudocode above would be implemented in the resampling functions so I don't think it would need a new flag. But we could also consider new "derived" flags that operate on rolling hourly windows or even a whole day. It's not obvious to me which approach would be easier for us, better for Topic Area 2 evaluations,or better for a generic end user.

Care to sample my can of worms @cwhanse @alorenzo175?

**Comment by alorenzo175** [comment]
I think what you're proposing, and what I agree with, is a revamp of the quality flag filtering. Instead of just excluding any flagged points prior to resampling, we should keep all points and assess during the resample.

Right now the processing of observation looks like
```python
filtered_obs = raw_obs[~times_flagged_with_any_selected_quality_flags]['value']
obs_mean, obs_count = filtered_obs.resample(fx_interval_length)
obs_series_to_compare = obs_mean.where(obs_count >= .1 * fx_interval / obs_interval)
```
what I'm proposing 
```python
obs_flags = quality_mapping.convert_mask_into_dataframe(raw_obs['quality_flag']) # bools w/ has columns like NIGHTTIME, CLEARSKY EXCEEDED
obs_flags['ISNAN'] = raw_obs['value'].isna()
resampled_flags = obs_flags.resample(fx_interval_length).sum()
to_discard = pd.Series(0, index=resampled_flags.index)
quality_flags_to_exclude += ['ISNAN']  # always drop periods with more than 10% nans
for flags in  quality_flags_to_exclude: 
    to_discard += resampled_flags[filter] > (0.1 * fx_interval / obs_interval) # more than 10% of points in interval were flagged
resampled_values = raw_obs['value'].resample(fx_interval).mean()
obs_series_to_compare = resampled_values[~to_discard]
```

I would also like to make the discard rule more configurable via more metadata in the QualityFlagFilter object. For example, discard periods that are > 90% nighttime, or discard periods that are < 95% clear. I think that more configurable filters are better than any more "derived" flags

**Comment by cwhanse** [comment]
I'm inclined to agree with @alorenzo175, that the analysis is better done by subsetting the resampled intervals, rather than the underlying data before resampling.

**Comment by wholmgren** [comment]
I'm digging into the `preprocessing.py` code. Here's one way forward:

1. `resample_and_align` becomes `resample_filter_align` and gains a `quality_flags` argument.
2. `_resample_obs` becomes `_resample_filter_obs` and gains a `quality_flags` argument.
3. `process_forecast_observations` loses its `validated_observations` cache. I suspect you'd need to compare a lot (> 10) of forecasts to the same observation to notice any difference in compute time. 

Another option:

1. `resample_and_align` becomes `resample_filter(fx_obs, obs_data, quality_flags)` and a separate `align(fx_obs, obs_data_resampled, fx_data, ref_data, tz)` function. `process_forecast_observations` calls `resample_filter` and then `align`.
2. `_resample_obs` becomes `_resample_filter_obs` and gains a `quality_flags` argument.
3. `process_forecast_observations` could keep the `validated_observations` cache if the keys became `(fxobs.data_object, fxobs.forecast.interval_length, fxobs.forecast.interval_label)`. I still don't think it's worth the complication.

Do we need to worry about the `QualityFlagFilter` metadata expansion now or can that be left to a separate PR? I don't see any major issues that require designing them together and I'm hoping that's a separate PR. I expect the `_resample_filter_obs` function would only need minor changes to support iterating over metadata in `QualityFlagFilter`. As another example, I think we previously discussed supporting different filters for different `forecast_observations`, and the workflows above wouldn't preclude that change.

**Comment by alorenzo175** [comment]
Option 1 sounds good to me, possibly w/ the separate resample and align functions. 

I think the ``QualityFlagFilter`` expansion can be left to a separate PR
