### ISSUE TITLE
queuing system design

### ISSUE THREAD

**Issue by alorenzo175** [SolarArbiter/solarforecastarbiter-core#57]
Things like observation validation and report generation will rely on a queuing/batch system. What will this look like? Maybe Celery will be useful for this

Tasks:
- [x] Choose framework (including a possible message queue if required)
- [x] Determine how authentication will work. Since all data requests will go through the API and the API requires a valid token from Auth0, how do we ensure each job has a valid token to call the API?
- [ ] Start with validating test data periodically

**Comment by alorenzo175** [comment]
I think [Dramatiq](https://dramatiq.io/index.html) is a good task processing library to start with. It is relatively easy to get up to speed and the codebase is fairly small and easy to extend if needed.

Redis looks like the easier broker to configure, but more research into the security of it is required.

**Comment by alorenzo175** [comment]
Redis should be reasonably secure on openshift if redis AUTH is used, NetworkPolicy is configured to only allow access to the redis pod from the dramatiq pods, and stunnel or spiped is used to encrypt data in transit

**Comment by alorenzo175** [comment]
For authentication, I think we should support both standard access tokens and refresh tokens if available. Right now, that means any job triggered by calling the API directly will need to run before the access token expires. But jobs triggered by the dashboard can include the refresh token and must run before the refresh token expires.

**Comment by alorenzo175** [comment]
Here is a basic example of how the queue might be used.

In some high level module like ``tasks.py`` all the queue functions will be defined. Each of these functions will get whatever data is necessary from the API, call functions to do work on this data, and store the final result. This might look like
```python
@dramatiq.actor
def validate_new_observation_data(access_token, observation_id, start, end):
    observation_model, observation_values = get_data(access_token, observation_id, start, end)
    quality_flags =  validation.validate_data(observation_model, observation_values)
    store_quality_flags(observation_id, quality_flags)
```

As the example shows, higher level functions to perform work like validation or report generation should expect objects from ``datamodel.py``, will be given the data in Pandas objects, and should return the result to be stored back in the database.

**Comment by wholmgren** [comment]
To be clear, my understanding of the data flow is something like

1. HTTP POST data to end point
2. API parses data but does not apply validation
3. If parsing is successful, API
     - inserts data in database
     - submits job to queue system. something like `validate_new_observation_data.send(access_token, observation_id, start, end)`
4. The queue system figures out which worker is going to do run the validation function
5. The queue worker runs the validation function, including inserting the results into the database

Did I miss anything @alorenzo175 ?

**Comment by alorenzo175** [comment]
That's right

**Comment by alorenzo175** [comment]
#82 adds the verification functionality that still needs testing w/ api

**Comment by alorenzo175** [comment]
immediate validation with a redis backend has been added
