### ISSUE TITLE
Possible issue with aggregate computation

### ISSUE THREAD

**Issue by lboeman** [SolarArbiter/solarforecastarbiter-core#587]
When looking into the requirements for https://github.com/SolarArbiter/solarforecastarbiter-dashboard/issues/160
I found some unexpected behavior when computing aggregates. My test aggregate has the following observation configuration:
```
'observations': [{'_links': {'observation': 'http://localhost:5000/observations/ca53af10-0cab-11eb-8b45-54bf64606445/metadata'},
   'created_at': '2020-10-14T16:41:20+00:00',
   'effective_from': '2020-01-01T00:00:00+00:00',
   'effective_until': None,
   'observation_deleted_at': None,
   'observation_id': 'ca53af10-0cab-11eb-8b45-54bf64606445'},
  {'_links': {'observation': 'http://localhost:5000/observations/123e4567-e89b-12d3-a456-426655440000/metadata'},
   'created_at': '2020-10-14T16:41:34+00:00',
   'effective_from': '2019-04-01T00:00:00+00:00',
   'effective_until': None,
   'observation_deleted_at': None,
   'observation_id': '123e4567-e89b-12d3-a456-426655440000'}],
```
I'm using the test `GHI Instrument 1` here with data between `2019-04-14T06:00Z` and `2019-04-17T06:55Z`.  I had thought that accessing the aggregate for that period should return the values of that observation, since the second observation's `effective_from` isn't until `2020-01-01`. But the API responds with "Cannot aggregate data with missing keys ca53af10-0cab-11eb-8b45-54bf64606445".

Is this the expected behavior?

**Comment by alorenzo175** [comment]
> Is this the expected behavior?

I don't think so, or at least it shouldn't be

**Comment by lboeman** [comment]
I think issue then lies with the code here: https://github.com/SolarArbiter/solarforecastarbiter-core/blob/1afe23c84dcb8065d1e6638bbff6696a650ae9e9/solarforecastarbiter/utils.py#L137-L150

Which asserts that all of the observations from `aggregate['observations']` exist in the data(regardless of effective_from/until). I think we want to assert that the observations in `valid_mask` with non-empty series exist in the data.

One caveat is that since this function checks for validity against the index of the data passed in instead of the start/end of the request, empty data validates just fine instead of showing the desired warnings. 

I think we could either:
- introduce start/end arguments to this function and either generate an index or extend the index of the data to start/end.
- Generate/extend indices in the API before calling this function. This would avoid bleeding the responsibility of knowing about the request into core.
 
@alorenzo175  Any thoughts on how to best approach this?

**Comment by alorenzo175** [comment]
> Generate/extend indices in the API before calling this function. This would avoid bleeding the responsibility of knowing about the request into core.

This sounds like the best option to me.

**Comment by alorenzo175** [comment]
maybe https://github.com/SolarArbiter/solarforecastarbiter-api/issues/255 can also be fixed by this change

**Comment by alorenzo175** [comment]
and https://github.com/SolarArbiter/solarforecastarbiter-api/issues/219
