### ISSUE TITLE
add data scripts to io

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-core#6]
@lboeman are we going to move your data scripts into this repo? I thought we decided yes when we discussed yesterday.

**Comment by lboeman** [comment]
Yes. Just opened #8 to do so.

**Comment by wholmgren** [comment]
Can we close this? I think so. If we need new data scripts then we should make issues for each of them.

**Comment by lboeman** [comment]
Yeah, More specific issues going forward if we need them would be good.
