### ISSUE TITLE
clean up optional and required dependencies

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-core#637]
I found the lists of optional and required dependencies to be confusing when addressing #636.

## `cli`

The following dependencies are required to simply run the command line tool's `solararbiter --help`:

click
sentry_sdk
aiohttp
loky
psutil

The first is no surprise and is in `EXTRAS_REQUIRE['cli']`. The last 3 are required because `cli.py` imports modules that need those packages, but they're only in `EXTRAS_REQUIRE['fetch']`. But `psutil` is also in `install_requires`

## `plotting`

`install_requires` contains:

bokeh
plotly
matplotlib

while `EXTRAS_REQUIRE['plotting']` contains:

bokeh
selenium

## proposed solutions

Option 1: reduce the `EXTRAS_REQUIRE` to be only `'test'` and `'all'` (for compatibility), put everything else in `install_requires`. Maybe plotting can remain separate.

Option 2: make `EXTRAS_REQUIRE['cli'] = the right stuff`

Option 3: reconfigure the imports so that `ImportError` is raised when running specific functionality instead of any of `cli`.

In any case we need to clean up the plotting specifications.

We should also 

- [x] add `python_requires='>=3.7, <4'
- [x] change `Development Status :: 3 - Alpha` to `Development Status :: 5 - Production/Stable`
- [x] add a "Documentation" key to `project_urls`
- [x] bump the pvlib requirement to 0.8
- [x] add `pytest-timeout` to `EXTRAS_REQUIRE['tests']`

We might also want to 

- [x] ~change `Programming Language :: Python :: 3.7` to `Programming Language :: Python :: 3` so that we don't have to keep track of this.~
- [x] add min versions of the dependencies

**Comment by wholmgren** [comment]
`pip install` and `conda install -c conda-forge` will pull in the latest versions of the dependencies and we have compatibility issues with some of them, so we should also 

1. add an unpinned, "latest" build to the ci
2. add a max version to requirements where relevant

**Comment by wholmgren** [comment]
@alorenzo175 do you have an opinion about the right way to proceed on cleaning up the optional/required dependencies? I'm leaning towards option 1.

**Comment by alorenzo175** [comment]
Fine with me to just have 'all' and 'test'. But, I would want to keep what's in `install_requires` to a small set that would enable users to use the APISession and other functions without installing the plotting packages for example. I'd say it's ok to require 'all' if someone wants to use the cli or make a report.
