### ISSUE TITLE
install on docker image fails

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-core#668]
see, for example, https://github.com/SolarArbiter/solarforecastarbiter-core/pull/661/checks?check_run_id=2309512088

```
tlmgr: Local TeX Live (2020) is older than remote repository (2021).
Cross release updates are only supported with
  update-tlmgr-latest(.sh/.exe) --update
See https://tug.org/texlive/upgrade.html for details.
```

@alorenzo175 is this a trivial fix? I don't know anything about tlmgr

**Comment by alorenzo175** [comment]
Yes, a rebuild of the docker image took care of it

**Comment by wholmgren** [comment]
Thanks!
