### ISSUE TITLE
unlink legend on/off for obs with same name in report time series

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-core#675]
Attempting to turn off one obs time series will turn off all time series in the plot below

<img width="869" alt="Screen Shot 2021-05-04 at 2 10 06 PM" src="https://user-images.githubusercontent.com/4383303/117070401-88a47e00-ace2-11eb-9a04-3037ee99b3bf.png">

<img width="870" alt="Screen Shot 2021-05-04 at 2 10 18 PM" src="https://user-images.githubusercontent.com/4383303/117070403-893d1480-ace2-11eb-8611-e9b48b1e47d2.png">

this is from https://dashboard.solarforecastarbiter.org/reports/b7176526-4ece-11eb-a2a8-0a580a820081

**Comment by wholmgren** [comment]
I think the new version of plotly might have something relevant to this.

Also worth considering if we should append the resample length the name for clarity and uniqueness.

**Comment by wholmgren** [comment]
And I'm not sure if this is a related plotting issue or something more critical, but we're only showing either the ending or beginning resampled obs despite the fact that the report contains forecasts with both for a few resolutions.

**Comment by lboeman** [comment]
How about this text in the legend? 
![Screenshot from 2021-07-30 16-10-53](https://user-images.githubusercontent.com/21206164/127720058-5c45e21e-ebe4-42fc-aba9-a625c5921d04.png)

**Comment by wholmgren** [comment]
I like it. And they operate independently?

**Comment by lboeman** [comment]
Yes. I've updated labels and adjusted the legendgroup, which seems like it was the issue.
