### ISSUE TITLE
Options for NIGHTTIME filter in reporting

### ISSUE THREAD

**Issue by williamhobbs** [SolarArbiter/solarforecastarbiter-core#697]
Additional options for the NIGHTTIME quality flag filter in reporting would be helpful, particularly to allow reports to include hours where some, but less than 90%, of the hour was during daytime while still excluding hours that were fully at night. Either making the resample threshold adjustable or adding a second version of a nighttime filter (perhaps with a 90 or 100% threshold) could address this.

As an example, here is a day from a report without the nighttime filter:
![image](https://user-images.githubusercontent.com/45701090/126834416-fbd130e3-4389-4823-876f-76c92599f9a4.png)

And here is the same day with the nighttime filter:
![image](https://user-images.githubusercontent.com/45701090/126834441-322c1e1d-f2f1-403c-9ef5-eb3ec0530dc8.png)

You can see that the filter removes the first and last hours, even though they include non-negligible generation (~5-10% of nameplate, in this example). The first hour in particular can be important in real-world operations.

**Comment by wholmgren** [comment]
The API supports an adjustable threshold but it's not exposed in the dashboard form. Unfortunately, the [API report post documentation](https://api.solarforecastarbiter.org/#tag/Reports/paths/~1reports~1/post) is not thorough enough to even give you hint at how it's done. 

@lboeman do you agree we can transfer this issue to the dashboard repository? And maybe a new issue in the API repo for documenting this?

**Comment by lboeman** [comment]
I think we need an API issue to improve the docs, but we have this one for the dashboard: https://github.com/SolarArbiter/solarforecastarbiter-dashboard/issues/367

**Comment by wholmgren** [comment]
Closed in the 1.0.5 release of the dashboard https://github.com/SolarArbiter/solarforecastarbiter-dashboard/issues/367
