### ISSUE TITLE
Probabilistic persistence forecasts constant

### ISSUE THREAD

**Issue by alorenzo175** [SolarArbiter/solarforecastarbiter-core#698]
The probabilistic persistence forecasts being made are constant for each constant value. 

https://dashboard.solarforecastarbiter.org/forecasts/cdf/9d8256ae-eb37-11eb-b73b-0a580a820178
![image](https://user-images.githubusercontent.com/4625457/126837735-70ce0e91-b51d-47e2-9c5d-4d98191cde3b.png)

The job workers that made this forecast *should* be calling `reference_forecasts.main:make_latest_probabilistic_persistence_forecasts` which gets down to `reference_forecasts.persistence:persitence_probabilistic_timeofday`

**Comment by alorenzo175** [comment]
Hmm seems to work correctly when running locally. And from above, where are the forecasts for July 24  that should have been generated at 2021-07-23T07:00Z?

**Comment by alorenzo175** [comment]
It may be that the data there was not generated by v1.02. Probably best to wait a few days and see what new forecasts look like

**Comment by wholmgren** [comment]
Appears to be working. Hopefully issue was as described.

<img width="863" alt="Screen Shot 2021-07-30 at 10 49 44 AM" src="https://user-images.githubusercontent.com/4383303/127692394-58c09e32-9d29-4149-8e0c-a8ce79d53c0d.png">
