### ISSUE TITLE
validation steps for each variable

### ISSUE THREAD

**Issue by alorenzo175** [SolarArbiter/solarforecastarbiter-core#71]
In order to be able to run the validation step on observations, we first need to know which functions in ``validator.py`` need to run. The general idea is that a higher level function will queue up a job. That job will get the observation data, call the right validation functions, and store the result back in the database.

The variables are defined in ``datamodel.py`` and are:
```python
ALLOWED_VARIABLES = {
    'surface_temperature': 'degC',
    'surface_wind_speed': 'm/s',
    'ghi': 'W/m^2',
    'dni': 'W/m^2',
    'dhi': 'W/m^2',
    'poa_global': 'W/m^2',
    'relative_humidity': '%',
    'ac_power': 'MW',
    'dc_power': 'MW',
    'availability': '%',
    'curtailment': 'MW',
}
```

For some variables, there may be no validation functions to run. To start, we need a mapping between the variables and a list of validation functions (in order if necessary). We'll have to decide how this will be implemented in the code (maybe a dict or a function that returns a set of functions to run) but that can come later.

@cwhanse can you make this list between variables and validation functions?

**Comment by cwhanse** [comment]
For ghi, dni or dhi: check_irradiance_day_night  I'd probably do this first before any of the other checks.  It labels day/night periods.  What is done with the labels should be discussed as a model for the other validation testing.  Do we display the results and ask the framework user to make a choice?  

With ghi only: check_irradiance_limits_QCRad then check_ghi_clearsky

With ghi, dni and dhi together: check_irradiance_limits_QCRad first, then check_ghi_clearsky applied to ghi, then check_irradiance_consistency_QCRad

For surface_temperature: check_temperature_limits

For surface_wind_speed: check_wind_limits

For any measured data: check_timestamp_spacing

For measured GHI, ac_power or dc_power: detect_stale_values, then detect_interpolation

For measured ac_power: detect_clipping probably last in sequence (this function is in a PR)

Currently there is no value checking for poa_global or relative_humidity, tests should be added.

There is no value checking for availability or curtailment, either, but I think these data are checked by overlaying the data on measured ac_power, along with the output of detect_clipping

**Comment by alorenzo175** [comment]
The current thinking on what would happen with the results is described in https://github.com/SolarArbiter/solarforecastarbiter-core/issues/57#issuecomment-485881215. Basically, a user will upload observations and if they pass the formatting requirements, they are inserted into the database. Then, a validation job will be queued up and will eventually run the validation functions and store the result of each test encoded as an integer described in #72. 

The decision about what to do with data that is flagged by the validation functions is then decided when metrics are calculated/reports generated. The user will be able to see the validation results and can fix and re-upload data if necessary. 

Does this sound reasonable? I also remember that there was some discussion of only running validation once a day on the full day of data. Is that desirable for any of the current validation functions?

**Comment by cwhanse** [comment]
If I was a framework user, I think that the sooner that validation checks are conveyed after data upload, the more I would value the content.  If, for example, I upload data, and am notified 2 days later that there's issues with the data, I may be more annoyed that I have to rewind in my work to go fix the issues, than if there was near-real time feedback at the time of upload.

**Comment by alorenzo175** [comment]
I agree that a quick notification of any issue after manually uploading the data is useful. To keep the API responsive, I think we'd still want to conditionally accept the data, but make sure the validation job is run within a few minutes. We can then send a message to the dashboard on the status of the validation, and maybe users can opt in to emails about validation in beta+ versions.

**Comment by wholmgren** [comment]
I remember that, for "real-time" data feeds, we discussed the possibility of running verification as the data was submitted and then **re**running verification each night. I think we were mostly concerned about this for AC power that could be clipped or curtailed. I don't think we ever developed a good sense of if it would really be necessary or a clear plan of what it would look like in practice.

A related issue that we discussed was that verification scripts may need to operate on more than just the single upload. For example, I think some of the functions will struggle with a single data point of hourly average data that is uploaded every hour.

**Comment by cwhanse** [comment]
Good points. 

Point-in-time checks: check_irradiance_limits_QCRad, check_ghi_clearsky, check_irradiance_consistency_QCRad, check_temperature_limits, check_wind_limits, check_rh_limits, check_timestamp_spacing

Checks requiring a time series: detect_stale_values, detect_interpolation, detect_clipping.  For these, I suggest requiring at least 24 hours(?) of data?  Or 10+ data points.  With shorter time series the code should run but the output is probably not useful.

**Comment by alorenzo175** [comment]
with #97 and #82, most of the validation should run. However, verification that requires multiple observation series (e.g. ghi, dni, and dni or ac power and curtailment) is not implemented.

**Comment by wholmgren** [comment]
@alorenzo175 should this be closed too? "In Progress to Done" suggests yes, though it sounds like maybe a new issue should be created for verification algorithms that use multiple series.
