### ISSUE TITLE
Misaligned data in report CSV

### ISSUE THREAD

**Issue by williamhobbs** [SolarArbiter/solarforecastarbiter-core#713]
I have a custom report with multiple forecasts. Some of the forecasts have been running since the beginning of the report start date, but others did not start until after the report start date. See the image below for a cropped version the first chart from the report (with only 2 forecasts selected), and note the approx. 3 week delay before the greenish-yellow forecast begins:

![image](https://user-images.githubusercontent.com/45701090/129804738-6c0b8757-d4dd-4ebb-9705-81eea9b0b61f.png)

When I download the CSV format version of the data, the forecast timeseries are misaligned such that they all have the same start date and time. See the spreadsheet chart below, where I tried to match the chart colors (note that the x-axis is simply row # from the CSV):

![image](https://user-images.githubusercontent.com/45701090/129805390-ac6fb648-48bb-49e9-8a55-21ba60216e00.png)

**Comment by lboeman** [comment]
Thanks for the report @williamhobbs! This looks like another, undocumented symptom of #707.
