### ISSUE TITLE
Add functionality to exclude periods of data from reports

### ISSUE THREAD

**Issue by lboeman** [SolarArbiter/solarforecastarbiter-core#730]
After a recent outage, we realized we need a way to exclude periods of data where users may not have been able to supply data through no fault of their own (e.g. in the case of an arbiter outage). 

We could force this exclusion in the meantime by adding "USER FLAGGED" to the observations in question. This should only be an option when the observations are only used in the trial/report.

**Comment by wholmgren** [comment]
Incomplete ideas: 

1. a new flag like "API UNAVAILABLE". 
2. Add unavailable times to forecast metadata. 

What we really care about is "was API unavailable at forecast issue time?" Observation data flags are a bad fit for that. And it's potentially different for different forecasts within a report, so report level information might also be problematic.
