### ISSUE TITLE
validator - passing DataFrames or Series

### ISSUE THREAD

**Issue by cwhanse** [SolarArbiter/solarforecastarbiter-core#76]
The earlier validator functions expect DataFrame arguments and return DataFrames.

Is that the behavior we want?  I recall a preference to not pass DataFrames, but rather a Series for each key value.

**Comment by wholmgren** [comment]
You recall correctly. We prefer to pass and return Series.

**Comment by cwhanse** [comment]
OK.  I'll convert the other function to Series in one PR answering this issue.
