### ISSUE TITLE
Ability to query NWP data thru an API

### ISSUE THREAD

**Issue by MichaelHopwood** [SolarArbiter/solarforecastarbiter-core#777]
Hello, I have looked through the documentation quite a bit and have had trouble finding a command which queries NWP results through an API, if one exists. I'm looking for some sort of function like:

```py
ghi_prediction_results = function( date_range, longitude, latitude, altitude, **aargs, **kwargs)
```

I found `solarforecastarbiter.reference_forecasts.models.gefs_half_deg_to_hourly_mean` but was met with a `FileNotFoundError`, namely:

```
FileNotFoundError: gefs\2020\01\01\12\gefs_c00.nc does not exist
```

I expect I'm not understanding something crucial.

Thanks in advance for the guidance :)

**Comment by wholmgren** [comment]
NWP data is not available through the SFA API. You can run the CLI tool `solararbiter fetchnwp` to download relevant data from NOAA servers to your machine. https://solarforecastarbiter-core.readthedocs.io/en/latest/cli.html

**Comment by MichaelHopwood** [comment]
Gotcha, thanks!
