### ISSUE TITLE
sketch of report workflow

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-core#87]
Report generation might follow steps like those the below. I'm sure I'm missing plenty of things and will edit after discussions.

1. User navigates to "Reports" page
1. User clicks "Create New Report" button
1. User inputs:
   * Name
   * 1 or more Observation/Forecast combinations (hopefully nice html+javascript to make this easy). Site is inherited from Observation and Forecast, so no need to specify separately (and avoiding site spec lets a user compare obs/forecast pairs across sites/aggregates).
   * start, end
   * some combination of validator flags, time of day, year, value filters.
   * selects metrics. List needs to be consistent with forecast type
   * maybe set missing data behavior
1. User clicks submit
1. API checks that forecast/observation combinations are valid
   * variable consistency (could be ensured in obs/fx selection process)
   * interval length, label (probably will be a core function for this)
   * maybe more
1. If valid inputs, API creates report metadata with correct permissions. Permissions probably rw for user that created the report and none otherwise.
1. API uses queue system to initiate report generation
1. Queue system calls core to generate report
   * Metrics requirements as described in #4.
1. Core writes out metrics report to storage. Storage might be a directory for now.
1. Core might also write out a file with the *aligned* observations, quality flags, and forecasts. This file supports reproducibility and transparency. Downside is duplication of data and raises questions about practical ability for users to revoke access to their data. No file for now.

I'll make a separate issue for report rendering in different formats.

A trial will make use of or extend a lot of this, but I think we can worry about that separately.

**Comment by wholmgren** [comment]
Art:

![report_list_and_form](https://user-images.githubusercontent.com/4383303/57790322-5cefee00-76ef-11e9-81b1-b3ce70233171.JPG)
![report_web](https://user-images.githubusercontent.com/4383303/57790323-5cefee00-76ef-11e9-830a-de6de6c92e06.JPG)

**Comment by alorenzo175** [comment]
updates:

  9. Core writes out metrics report to storage. Storage will be the database via a post to the API.
  10. Core will write out aligned observations, quality flags, and forecasts via a post to the API. This data will be stored in a separate table in the database and any user retrieving the data need to have the read_values permission for the parent observation/forecast. This maintains reproducibility and transparency while adding a mechanism to revoke access to the data.

**Comment by wholmgren** [comment]
closed by #132
