### ISSUE TITLE
start running nwp reference forecasts

### ISSUE THREAD

**Issue by alorenzo175** [SolarArbiter/solarforecastarbiter-core#90]

**Comment by alorenzo175** [comment]
at least some example forecasts are available at https://dashboard.solarforecastarbiter.org/forecasts/single/?uuid=9f61b880-7e49-11e9-9624-0a580a8003e9

cc: @wholmgren

**Comment by wholmgren** [comment]
@alorenzo175 closed by #127?

**Comment by alorenzo175** [comment]
yes
